### ISSUE TITLE
Epic: Squish: Automate the most frequently used manual tests

### ISSUE THREAD

**Issue by HanaGemela** [owncloud/client#10973]
Prioritites:

# p1
- [x] https://github.com/owncloud/client/issues/9833
- [x] https://github.com/owncloud/client/issues/11346
- [x] Regression Test Vanilla
  - https://github.com/owncloud/client/issues/11653
- [ ] Reconnect after Maintenance mode was encountered

# p2 
- [ ] Regression Test OEM
- [ ] OEM parameter specific test cases

# p3
- [ ] LDAP / UUID https://github.com/owncloud/client/issues/8971 (1.9)

# Non squish
- [ ] owncloudcmd

**Comment by fmoc** [comment]
Please provide a status update (and ideally a more accurate title, the current one is a bit misleading).

**Comment by HanaGemela** [comment]
Automation of Regression Test Vanilla in progress
