### ISSUE TITLE
New linux packages test plan

### ISSUE THREAD

**Issue by HanaGemela** [owncloud/client#11171]
To keep track of progress of testing:
https://github.com/owncloud/client/issues/10702
https://github.com/owncloud/client/issues/11059
https://github.com/owncloud/client/issues/11080

**ownCloud desktop client** 

Fedora @saw-jan (`ownCloud 5.0.0.12034-daily20230905`)
- [x] upgrade from 4.2 to 5.0 successful
- [x] icons are available in /usr/share/icons whose filenames matches /usr/share/applications/<shortname>.desktop's Icon= entry 
- [x] overlay icons in file manager are present
- [x] owncloud context menu is available in file manager 
- [x] free up space creates file.owncloud and when opened the actual file is downloaded and displayed
- [x] syncing works

Ubuntu ( @Salipa-Gurung ) (`ownCloud 5.0.0.12024-daily20230904`)
- [x] upgrade from 4.2 to 5.0 successful
- [x] icons are available in /usr/share/icons whose filenames matches /usr/share/applications/<shortname>.desktop's Icon= entry 
- [x] overlay icons in file manager are present (Nautilus)
- [x] owncloud context menu is available in file manager 
- [x] free up space creates file.owncloud and when opened the actual file is downloaded and displayed
- [x] syncing works
- [x] Conflicts: install the distro-provided owncloud-client, owncloud-client-cmd and owncloud-client-data on Ubuntu 22.04. Then install the client using the 5.0 dailies Linux repositories and run an upgrade. The cmd and data packages should be removed upon the upgrade because they are replaced by the -client package. https://github.com/owncloud/client/issues/11057
- [x] Crash reporter works

Debian ( @Salipa-Gurung ) (`ownCloud 5.0.0.12024-daily20230904`)
- [x] upgrade from 4.2 to 5.0 successful
- [x] icons are available in /usr/share/icons whose filenames matches /usr/share/applications/<shortname>.desktop's Icon= entry 
- [x] overlay icons in file manager are present
- [x] owncloud context menu is available in file manager 
- [x] free up space creates file.owncloud and when opened the actual file is downloaded and displayed
- [x] syncing works
- [x] Conflicts: install the distro-provided owncloud-client, owncloud-client-cmd and owncloud-client-data on Debian 12. Then install the client using the 5.0 dailies Linux repositories and run an upgrade. The cmd and data packages should be removed upon the upgrade because they are replaced by the -client package. https://github.com/owncloud/client/issues/11057

openSUSE @saw-jan 
- [x] upgrade from 4.2 to 5.0 successful ❗ Failed https://github.com/owncloud/client/issues/11188#issue-1885321796
- [x] icons are available in /usr/share/icons whose filenames matches /usr/share/applications/<shortname>.desktop's Icon= entry 
- [x] overlay icons in file manager are present (Dolphin)
- [x] owncloud context menu is available in file manager 
- [x] free up space creates file.owncloud and when opened the actual file is downloaded and displayed
- [x] syncing works

**QA client**

Ubuntu 22.04 (@HanaGemela) 
- [x] upgrade from 4.2 to 5.0 successful (:x: https://github.com/owncloud/client/issues/11171#issuecomment-1705026331) 
- [x] icons are available in /usr/share/icons whose filenames matches /usr/share/applications/<shortname>.desktop's Icon= entry 
- [x] overlay icons in file manager are present 
- [x] owncloud context menu is available in file manager 
- [x] syncing works

**QA client**

Latest stable Fedora  (@HanaGemela) 
- [x] upgrade from 4.2 to 5.0 successful - using example script https://github.com/owncloud/client/issues/10702 
- [x] icons are available in /usr/share/icons whose filenames matches /usr/share/applications/<shortname>.desktop's Icon= entry 
- [x] overlay icons in file manager are present
- [x] owncloud context menu is available in file manager 
- [x] syncing works
- [x] Crash reporter works

**Install test script**  (@jnweiger)
- [ ] Install test script passed https://github.com/owncloud/client/issues/11061

**Comment by Salipa-Gurung** [comment]
For testpilotcloud client 
Ubuntu 22.04

Upgrade from 4.2 to 5.0 not successful

**Comment by fmoc** [comment]
This does not seem to occur with the `ownCloud` theme. Investigating.

**Comment by saw-jan** [comment]
Vanilla upgrade (`openSUSE 15.4`):

After the upgrade from 4.2, desktop-client doesn't have toolbar. Any missing packages that I have to install?

![Screenshot from 2023-09-06 17-02-26](https://github.com/owncloud/client/assets/52366632/fe3ec2f6-2be9-4615-96f1-a105d0910c06) | ![Screenshot from 2023-09-06 16-40-45](https://github.com/owncloud/client/assets/52366632/9e1cf1e1-1646-440d-b0e3-d83a82d4be66)
--|--
4.2 | 5.0

**Comment by HanaGemela** [comment]
Icons:

```
cd /usr/share/applications/
cat qaclient.desktop
```

[Desktop Action Settings]
Exec=qaclient --showsettings
Name=Show QA Client settings
**Icon=qa**

```
cd /usr/share/icons/
find -name "qa.*"
```

./hicolor/512x512/apps/qa.png
./hicolor/48x48/apps/qa.png
./hicolor/128x128/apps/qa.png
./hicolor/256x256/apps/qa.png
./hicolor/1024x1024/apps/qa.png
./hicolor/64x64/apps/qa.png
./hicolor/32x32/apps/qa.png

✅

**Comment by HanaGemela** [comment]
Moving to Done as the manual tests passed. The last automated steps will be tracked separately here https://github.com/owncloud/client/issues/11061

**Comment by fmoc** [comment]
> But latest daily (ownCloud 5.0.0.12103-daily20230912 [035c42]) doesn't show this problem.

I think @TheOneRing removed the Qt Wayland plugin from the packages, forcing Wayland users to use the `xcb` platform theme automatically. This fixes a variety of problems and apparently doesn't introduce any problems.
