### ISSUE TITLE
Regression test for 5.1.0 release

### ISSUE THREAD

**Issue by HanaGemela** [owncloud/client#11284]
Tests

- [x] [regression test](https://owncloud.testrail.io/index.php?/cases/view/2402&group_by=cases:section_id&group_order=asc&display_deleted_cases=0&group_id=296)
- [x] Platform install test

Upgrade from distro package to the new 5.1 package (@saw-jan)

- [x] Ubuntu
- [x] Debian 
- [x] Fedora
- [x] openSUSE

Upgrade from the 4.2 package to the new 5.1 package following the upgrade instructions on the download page (@saw-jan)

- [x] Ubuntu
- [x] Debian (@Salipa-Gurung)
- [x] Fedora
- [x] openSUSE

Ubuntu extensions - Ubuntu 22.04

- [x]   owncloud-client-overlays-icons
- [x]   owncloud-client-nemo
- [x]   owncloud-client-nautilus
- [ ]   owncloud-client-dolphin ❗  https://github.com/owncloud/client/issues/11309
- [x]   owncloud-client-caja

Debian extensions - Debian 11

- [x]   owncloud-client-overlays-icons
- [x]   owncloud-client-nemo
- [x]   owncloud-client-nautilus
- [ ]   owncloud-client-dolphin ❗  https://github.com/owncloud/client/issues/11309
- [x]   owncloud-client-caja

Fedora extensions - Fedora 38

- [x] owncloud-client-overlays-icons
- [x] owncloud-client-nemo
- [x] owncloud-client-nautilus
- [x] owncloud-client-dolphin
- [x] owncloud-client-caja

openSUSE extensions - openSUSE 15.4

- [x] owncloud-client-overlays-icons
- [x] owncloud-client-nemo ❗ https://github.com/owncloud/client/issues/11311
- [x] owncloud-client-nautilus
- [x] owncloud-client-dolphin
- [x] owncloud-client-caja

Tested with 5.1.0 RC1

**Comment by HanaGemela** [comment]
Linux platform install tests:
Fedora 39:  [test_20231023_1211.log](https://github.com/owncloud/client/files/13069014/test_20231023_1211.log)
Other platforms: [test_20231020_1100.log](https://github.com/owncloud/client/files/13069021/test_20231020_1100.log)
