### ISSUE TITLE
[a11y] 2.1.1 Usable without mouse

### ISSUE THREAD

**Issue by tschiebel** [owncloud/client#11584]
https://infinite.owncloud.com/s/KcGPhbRgJfHYHuw

[BIT inklusiv BITV-Softwaretest - BIT inklusiv (bit-inklusiv.de)](https://www.bit-inklusiv.de/bitv-softwaretest/)

### Space 

- [x] #11772
![image](https://github.com/owncloud/client/assets/132444655/611c5056-5f0d-49f8-9319-6f10aa3be9d8)

- [x] The button with the three dots, which opens a menu, can neither be focused nor activated with the 
neither focused nor activated with the keyboard.
![image](https://github.com/owncloud/client/assets/132444655/30c51981-eed7-43e6-af25-7cb21c93f855)

###  Synchronization protocol

- [x] The table offers the option of sorting the contents by activating the 
column headings are activated. However, this function is only available to 
available to mouse users. It is not possible to use the keyboard to 
focus and activate the column headings. Instead, you can only access 
the individual data cells, which makes no sense. 
![image](https://github.com/owncloud/client/assets/132444655/2f778fed-b27d-4aac-8fd2-fea172dace0b)

### Add Space 

- [x] The table offers the option of sorting the contents. Sorting is triggered 
triggered by activating the column headings. However, this 
this function is only available to mouse users. It is not possible to use the keyboard 
not possible to focus on and activate the column headers, 
although this is possible for the individual data cells. This does not result in a 
meaningful context.
![image](https://github.com/owncloud/client/assets/132444655/27fed5e6-d913-4d8c-8bf2-4f78f2219bba)
 
- [x] In the test, it was not possible to activate the radio buttons in the 
"Synchronize" column using the keyboard. When activating with 
the ENTER key, you unexpectedly landed on the "Select a local folder" page. 
local folder". This is because the "Next" button was also active. A 
similar problem also affects other elements in the table.
