### ISSUE TITLE
[QA] Automate GUI regression tests

### ISSUE THREAD

**Issue by ishabaral** [owncloud/client#11999]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the QA issue

- [ ] The spaces count is 0 out of 0 when adding the new account. However, after restarting the client, the count is correct. https://github.com/owncloud/client/issues/11889
- [ ] [Win] Cannot enable VFS after disabling it https://github.com/owncloud/client/issues/11566
- [ ] The AUT Crashed when confirming the folder sync connection removal of oC10 account https://github.com/owncloud/client/issues/11814
  - Steps to reproduce:
     1. Add a new account
     2. Remove folder sync connection
     3. Confirm Folder Sync Connection Removal on the dialog box

### Steps to reproduce the issue

1. Add a new account
2. Remove folder sync connection
3. Confirm Folder Sync Connection Removal on the dialog box

### Screenshots

![remove_folder_sync_connection](https://github.com/user-attachments/assets/53cb69fe-bfd5-4f7a-9fb0-d80a317f5910)

**Comment by Dem0n52431** [comment]
Domain: CWE-79
