### ISSUE TITLE
Rename the mirall repo

### ISSUE THREAD

**Issue by craigpg** [owncloud/client#2470]
This issue captures the ToDo list for renaming the "mirall" repo to "client".  The goal is to think this through so there are no surprises, especially when it comes time to do a release.  Here goes:

Please note that GitHub will automatically redirect requests from the old repo name to the new one, so requests to owncloud/mirall should be handled by owncloud/client seamlessly.  This _might_ make some of ToDos below a little less onerous.

#### ToDos
- [x] Prepare: Eliminate the word "mirall" in the sourcecode?
- [x] Prepare: Change all the cmake build scripts
- [x] Merge changes into master
- [x] Rename repo in GitHub
- [x] Change/test the Windows and Mac build infrastructure
- [x] Change/test the linux packaging scripting that we use for example in Jenkins
- [x] Change/test the branding build scripts
- [x] Change other little scripts to copy stuff from here to there
- [x] Translation automatization

**Comment by dragotin** [comment]
tarballname created by jenkins is owncloudclient-<version>.tar.bz2 from 1.8.0 on.

**Comment by dragotin** [comment]
@danimo still wants to rename the transifex repository which is still mirall.

**Comment by danimo** [comment]
Done.

**Comment by dragotin** [comment]
Cool, thanks. Lets close this one.
