### ISSUE TITLE
Server version 8.1 Wishlist

### ISSUE THREAD

**Issue by dragotin** [owncloud/client#2725]
This page collects a list of issues that we provide as an input for our server friends for their discussion about the version 8.1 raodmap.

* [x] Ability to deal with highly parallelized requests, in  particular parallel chunk upload, see https://github.com/owncloud/client/issues/2724 

* [x] ...But also for MKCOL and DELETEs and MOVEs

* [ ] Checksum secured file transmission (GET and PUT). The server's backend should calculate  checksums along the file upload and provide the result as a reply header, so that the client can double check if the file arrived properly. Same for download. This depends on https://github.com/owncloud/core/issues/12417

* [ ] Asynchronous Actions, ie. assembling of a chunked upload, trashbin handling etc., see
 https://github.com/owncloud/core/issues/12097 

* [ ] Improved performance for upload of small files: https://github.com/owncloud/core/issues/12001 (in general make individual requests fast so we could increase client side parallelism)

* [ ] Performance improvements especially for large shared file sets.

* [x] Check whether receiving the quota is a cheap operation (we were told it is but it seems to sometimes bring our whole sync down)

Also, the "server involved" bug reports in the client repo should be considered: https://github.com/owncloud/client/issues?q=is%3Aopen+is%3Aissue+label%3A%22Server+Involved%22

**Comment by rullzer** [comment]
- [ ] Ability to retrieve users and groups on the server to allow sharing with users and groups from the sharedialog

**Comment by dragotin** [comment]
- [ ] an ownCloud app that enables us to test server side error states in our integration tests. It would do nothing else than returning a http error code when a certain file is accessed through a http request. That would be a great improvement to QA.

**Comment by guruz** [comment]
* [ ] Two pushes of the same file at about the same time result in no changes in the etag. https://github.com/owncloud/core/issues/7802

**Comment by guruz** [comment]
* [ ] Make sure server's sqlite3 DB glue sets a busy wait handler so we don't get problems when syncing (with parallel requests) and the server DB is locked. https://github.com/owncloud/core/issues/10566#issuecomment-71024979 https://github.com/owncloud/client/issues/2724#issuecomment-71005940

**Comment by dragotin** [comment]
@craigpg this is our Wishlist for server 8.1 which you asked for.

**Comment by craigpg** [comment]
Thx guys.  @karlitschek, @MTRichards.

**Comment by rullzer** [comment]
> - [ ] Ability to retrieve users and groups on the server to allow sharing with users and groups from the sharedialog

This is basically done in pull request https://github.com/owncloud/core/pull/13587

**Comment by DeepDiver1975** [comment]
@dragotin lets work on this list everytime we meet in N - okay?

**Comment by dragotin** [comment]
yes.

**Comment by PVince81** [comment]
You forgot to mention.
- [ ] stable file ids: https://github.com/owncloud/core/issues/13310

**Comment by PVince81** [comment]
stable file ids is done 8.1, except for the trickiest case when files are changed on remotely on external storages:
- [ ] stable file ids when file remotely changed on external storage: https://github.com/owncloud/core/issues/11533

**Comment by butonic** [comment]
- [ ] use all cores when discovering files

**Comment by moscicki** [comment]
@PVince81: stable files ids are a concept "broken by design" for generalized sync purposes, please refer to this document: https://github.com/cernbox/smashbox/blob/master/protocol/protocol.md#lifecycle-and-semantics-of-fileid-vs-path-vs-etag

**Comment by guruz** [comment]
@butonic 
> use all cores when discovering files

What is this about? Is this about the server file cache?

**Comment by butonic** [comment]
@guruz No, the client seems to only use a single core during the initial sync. It is at 100% for a long time. There seems to be a performance improvement opportunity hidden in there.

**Comment by MTRichards** [comment]
Adding as it is a dependency for checksums: https://github.com/owncloud/core/issues/11811

**Comment by PVince81** [comment]
>Check whether receiving the quota is a cheap operation (we were told it is but it seems to sometimes bring our whole sync down)

It is only cheap if the quota is already known by the server.
In some cases when files/folders weren't scanned yet it might trigger a scan, which might in some cases take a long time to compute the total size.

Maybe we should find another way for calculating the quota in a much quicker manner (single SQL) when requested that way.

**Comment by PVince81** [comment]
with "quota" I mean used space.

**Comment by guruz** [comment]
Simpler version of the checksum proposal: https://github.com/owncloud/core/issues/18716

**Comment by MorrisJobke** [comment]
> Two pushes of the same file at about the same time result in no changes in the etag. owncloud/core#7802

This should be fixed meanwhile with high level file locking (optional in 8.1 and enabled by default in 8.2)

**Comment by dragotin** [comment]
Closing in favour of #4558
