### ISSUE TITLE
[Meta bug] Clarify and clean HTTP and HTTPS / SSL redirection issues

### ISSUE THREAD

**Issue by guruz** [owncloud/client#2791]
- [x] https://github.com/owncloud/client/issues/1735
- [x] https://github.com/owncloud/client/issues/1118
- [x] https://github.com/owncloud/client/issues/1616

Also:
- [x] https://github.com/owncloud/client/issues/1478

**Comment by guruz** [comment]
Also https://github.com/owncloud/client/issues/3226

FYI @danimo @ckamm @LukasReschke

**Comment by ckamm** [comment]
#3226 is done, but #3251 is a related enhancement proposal

**Comment by guruz** [comment]
Moving to 2.1 as this is not doable in the current timeline

**Comment by guruz** [comment]
Another candidate https://github.com/owncloud/client/issues/3284

**Comment by guruz** [comment]
Discussed with @danimo @ogoffart 

This is interweaved with the captive portal issues

* We always want to follow redirects in the setup Wizard (Done!)

In future:
When having a http:// server URL:
* If we when requesting status.php get a redirect to https:// with same host (port doesn't matter) then we follow it.
* If we when requesting status.php get any other redirect we go offline.

When having a https:// server URL:
* If we get a redirect when requesting status.php (to a URL also mentioning status.php) to https:// we also accept it (assuming there is no SSL errors..)
* If we in normal operation get a SSL warning (e.g. self signed certificate by captive portal) we go offline and retry the connection in some minutes (captive portal) (Still unclear how to best implement this with Qt's API) (note we must still show the SSL warning dialog in case the user manually sets his/her account to login again)

FYI @LukasReschke

**Comment by LukasReschke** [comment]
> If we when requesting status.php get a redirect to https:// with same host (port doesn't matter) then we follow it.

Should we maybe also store this information to prevent MITM once the client gets restarted?

**Comment by guruz** [comment]
We were thinking when we receive a redirect that we accept as "new URL" then we also store that in the config.

**Comment by LukasReschke** [comment]
:+1: :rocket:

**Comment by SamuAlfageme** [comment]
Somehow *related* with this happens when trying to access an https endpoint of the server via `http://` protocol, server just replies with 400: Bad Request [instead of redirecting to the SSL endopoint](http://stackoverflow.com/questions/4083221/how-to-redirect-all-http-requests-to-https). 

![screen_shot_2016-12-13_at_17_58_50](https://cloud.githubusercontent.com/assets/2644445/21150315/e2b93616-c15e-11e6-917f-23999bfb82e5.png)

If the URL stored was http and it suddenly switches to https. User will encounter with the equivalent: 

![screen_shot_2016-12-13_at_18_01_14](https://cloud.githubusercontent.com/assets/2644445/21150316/e2bab78e-c15e-11e6-9bff-f59db7391554.png)

Should we elevate this to core?

**Comment by guruz** [comment]
Might be mostly done with https://github.com/owncloud/client/issues/5972
Needs some verification

**Comment by ckamm** [comment]
@SamuAlfageme Do you still want to test something here? Since this is a meta issue and the linked tickets have been closed, I'd be up for closing this one too.

**Comment by SamuAlfageme** [comment]
@ckamm agreed, let's close here - I'll review SAML redirection behaviors before the 2.4 release, but so far I didn't see anything to worry about.
