### ISSUE TITLE
Multi Account

### ISSUE THREAD

**Issue by ogoffart** [owncloud/client#3084]
Note:  the work is currently done in the `master` branch

- [x] Refactor libowncloudsync to always have an AccountPtr and not rely on a global one
- [x] Investigate all remaining uses of `AccountManager::instance()->accounts().value(0)`
- [x] Store folders below accounts in config
- [x] GUI: adapt the setup wizard
- [x] GUI: put account list in the top bar
- [x] GUI: put account list in the top bar (Mac)
- [x] GUI: Systemtray icon adaptation
- [x] Migration from old config
- [ ] port `accountmigrator.cpp`  -> #3515
- [x] Adapt the ShareDialog
- [x] Do something with general error  (AccountSettings::setGeneralErrors)
- [ ] Define a shorter displayName for Accounts or allow users to assign one -> #3516
- [x] Remove accounts
- [x] Set the logged in / logged out state per account
- [ ] Activity list
- [ ] Restriction in the theme for single account -> #3517

(This is an implementation ticket, please do not comment with anything not implementation-related)

**Comment by DavidRCrowe** [comment]
It is good news that this feature is making progress!

**Comment by ogoffart** [comment]
As of today, the branch is somehow working, but there is still some work to do before it can be merged to master.
The code currently is not working on mac, or not working with Qt4 and old compilers yet.
