### ISSUE TITLE
Server version 9.1 Wishlist

### ISSUE THREAD

**Issue by dragotin** [owncloud/client#4558]
This page collects a list of issues that we provide as an input for our server friends for their discussion about the version 9.1 roadmap. This is the successor of #2725 which I will close.
- [ ] Checksum verification on the server on upload of files owncloud/core#11811 
- [ ] Versioning API owncloud/core#10571 (client #4556) 
- [ ] Support for enhanced versioning owncloud/core#23002 (client #4557)
- [ ] Implementation of the new chunking API owncloud/core#20118
- [ ] Verification if we still need Async Actions as described in owncloud/core#12097
- [ ] Improvements with handling many small files: owncloud/core#12001 was closed, but no real alternative was decided on.
  FYI: Client 2.2 will pump in up to 6 requests at once (vs 3 with previous versions) if it sees the request as a small file (download, delete, mkdir, possibly uploads too)
- [ ] ownCloud Debug App to simulate error situations, see for example owncloud/smashbox#94
- [ ] Allow the clients to retrieve server avatars https://github.com/owncloud/core/issues/14564
- [ ] New activity API as discussed in owncloud/activity#405 (client #4208)
- [ ] Pull user specific configuration from the server, ie. owncloud/enterprise#1198

@MTRichards @karlitschek @cmonteroluque please consider

**Comment by karlitschek** [comment]
Thanks @dragotin

**Comment by poVoq** [comment]
Maybe the new semi-official XMPP php server/chat system could also notify the client about messages etc?

**Comment by danimo** [comment]
@poVoq Err, what?

**Comment by poVoq** [comment]
Ok maybe not quite as official as I though ;) Works great though:
https://www.jsxc.org/blog/2016/03/11/v3.0.0-released/

**Comment by dragotin** [comment]
Added an entry to the list: Pull user specific configurations from server, ie. #1198
