### ISSUE TITLE
Client 2.3.3 release

### ISSUE THREAD

**Issue by guruz** [owncloud/client#5889]
Some weeks before the release:
* [x] Check if we should update the bundled sqlite3 (https://github.com/owncloud/client/tree/master/src/3rdparty/sqlite3)
* [x] Check if we should update Sparkle on build machine (https://github.com/sparkle-project/Sparkle/releases)
* [x] Ensure NSIS is up to date on the build machine
* [x] Ensure up-to-date dependencies (e.g. [latest Qt version](http://qt-project.org/downloads#qt-lib) is installed on the machine and picked up (cmake output)
* [x] Ensure the crash reporter server is up
* [x] Check crash reporter for bad crashes
* [x] Ensure Windows Overlay DLLs are rebuilt
* [x] Check nightly builds are up and running, that is Jenkins jobs ownCloud-client-linux, ownCloud-client-osx and ownCloud-client-win32 all green.
* [x] Ensure Linux nightlies are built too for all distros https://build.opensuse.org/package/show/isv:ownCloud:community:nightly/owncloud-client
* [ ] Build branded clients through the scripting machine and smoke test one or two branded clients (especially with predefined url)
* [x] Upload a nightly build of the windows version to virustotal.com
  * Contact AV vendors whom's engine reports a virus
* [x] Documentation should be online before the release http://doc.owncloud.org/desktop/1.X/
* [x] QA goes over https://github.com/owncloud/mirall/wiki/Testing-Scenarios
* [x] Make sure to have `client/ChangeLog` updated
 * use `git log --format=oneline v<lastrelease>...master` if your memory fails you
* [x] check if enterprise issues are fixed

One week before the release:
* [x] Communicate the release schedule on mailinglist release-coordination@owncloud.com. Give a high level overview of the upcoming new features, changes etc.
* [ ] Ensure marketing is aware (marketing@owncloud.com) and prepared for the release (social, .com website, cust. communications)
* [x] Inform GCX knows the next version is about 1 week out (gcx@owncloud.com)

For all Betas and RCs:
* [x] Branch off a release branch called VERSION-rcX or VERSION-betaX  (without v, v is for tags)
* [x] Edit ```VERSION.cmake``` to set the suffix to beta1, beta2 etc. Commit the result to the release branch only
* [x] Create build for Windows using rotor job owncloud-client-win32 (uncheck the "nightly build" checkbox, check the "sign package" checkboxes) both themes 'ownCloud' and 'testpilotcould'
* [x] Create build for Mac using rotor, job owncloud-client-osx (uncheck the "nightly build" checkbox, check the "sign package" checkboxes) both themes 'ownCloud' and 'testpilotcould'
* [x] Create the beta tarball using Jenkins job ownCloud-client-source
* [x] Create Linux builds using rotor job owncloud-client-linux building (this magically interacts with the ownCloud-client-source job)
  * [x] theme 'ownCloud' -> isv:ownCloud:community:testing
  * [x] theme 'testpilotcould' -> isv:ownCloud:testpilot:testing
* [x] Copy builds from ```daily``` to ```testing``` on download.owncloud.com, double check the download links.
* [x] Create a pull request to the owncloud.org repository to update the install page (strings.php, page-desktop.php). From now on download packages from the staging webserver.
* [ ] Inform community mailinglists devel@owncloud.org and testpilots@owncloud.org
* [x] Announce on https://central.owncloud.org
* [x] Create a signed tag using ```git tag -u E94E7B37 tagname``` (https://github.com/owncloud/enterprise/wiki/Desktop-Signing-Knowledge)
* [ ] Check crash reporter

For first Beta of a Major or Minor release:
* [ ] branch off master to new version branch (e.g. master -> 2.1, when releasing 2.1)
* [ ] Adjust `VERSION.cmake` in master and count up (e.g. 2.2)
* [ ] Adjust translation jobs for [client](https://ci.owncloud.org/view/translation-sync/job/translation-sync-client/) and [NSIS](https://ci.owncloud.org/view/translation-sync/job/translation-sync-client-nsis/) to point to the release branch (e.g. 2.1).
* [ ] Make sure there is a job for the docs of the new master branch and the current release branch on rotor.

Day before Release:
* [x] Check the translations coming from transifex: All synchronized?
* [ ] Run the tx.pl scripts on the final code tag
* [ ] Run ```make test```
* [ ] Run smashbox on the final code tag
* [ ] Inform product management and marketing that we are 1 day out

On Release Day (for final release):
* [x] Branch off a release branch called like the version (without v, v is for tags)
* [x] Double check ```VERSION.cmake```: Check the version number settings and suffix (beta etc.) to be removed. Commit change to release branch only!
* [x] Make sure to increase the version number of the branched of release, e.g. if you release 2.3.2 then you should change VERSION.cmake in 2.3 to 2.3.3 since that branch now will be 2.3.3
* [ ] Add last updates to Changelog in the client source repository.
* [x] Stop publishing on OBS https://build.opensuse.org/project/show/isv:ownCloud:testpilot https://build.opensuse.org/project/show/isv:ownCloud:desktop
* [x] Branch isv:ownCloud:desktop to isv:ownCloud:desktop:client-X.Y.Z before overwriting https://github.com/owncloud/administration/blob/master/jenkins/obs_integration/obs-backup-prj.sh
* [X] Check download mirrors for sufficient free disk space (jw,tsgebert)
* [x] Run https://jenkins.int.owncloud.com/view/client/job/official-client-trigger with  (uncheck the "nightly build" checkbox, check the "sign package" checkboxes) both themes 'ownCloud' and 'testpilotcould'  this does all of the following (except for signing the sources):
  * [x] Create tar ball (https://jenkins.int.owncloud.com/view/client/job/official-client-source/) and **immediately** sign it (asc file). (https://github.com/owncloud/enterprise/wiki/Desktop-Signing-Knowledge)
  * [x] Create build for Windows using jenkins.int job official-client-win32 (uncheck the "nightly build" checkbox, check the "sign package" checkboxes) both themes 'ownCloud' and 'testpilotcould'
  * [x] Create build for Mac using jenkins.int, job official-client-osx (uncheck the "nightly build" checkbox, check the "sign package" checkboxes) both themes 'ownCloud' and 'testpilotcould'
  * [x] Create Linux builds using rotor job owncloud-client-linux (this magically interacts with the ownCloud-client-source job)
    * Check if patches still apply in the linux packages
  * Update [OBS repository](https://build.opensuse.org/project/show?project=isv%3AownCloud%3Adesktop) `isv:ownCloud:desktop`
    * [x] theme 'ownCloud' -> isv:ownCloud:desktop
    * [x] theme 'testpilotcloud' -> isv:ownCloud:testpilot
  * [x] Linux: Update the testing repository to the latest stable version.
* [ ] check remaining free disk space on the mirrors.
* [x] **immediately** sign the sources (asc file). (https://github.com/owncloud/enterprise/wiki/Desktop-Signing-Knowledge)
* [x] Linux: Create submitrequests in obs
  See https://github.com/owncloud/enterprise/wiki/Client-release-with-jenkins#final-release
* [ ] Inform GCX that a new tarball is available. Inform QA...
* [x] Copy builds and source tar ball from ```testing``` to ```stable``` on download.owncloud.com, double check the download links.
* [x] Check if the following packages are on download.owncloud.com/desktop/stable:
  * Windows binary package
  * Mac binary package
  * source tarballs
* [x] Create a pull request to the owncloud.org repository to update the install page (strings.php, page-desktop.php) for variables and changelog. From now on download packages from the staging webserver.
* [ ] Re-download Mac builds and check signature. Interactive in installer window
* [ ] Re-download Win build check signature. From Mac or Linux: ```osslsigncode verify ownCloud-version-setup.exe```
* [x] Mac: Perform smoke test (Install, make sure it does not explode, and check if all version indicators are correct)
* [x] Win: Perform smoke test (Install, make sure it does not explode, and check if all version indicators are correct)
* [x] Linux: Smoke test 
* [x] Linux: Re-enable OBS publishing
* [x] Announce on https://central.owncloud.org
* [x] Announce on announcements@owncloud.org
* [ ] Create git signed tag in client repository using ```git tag -u E94E7B37 tagname```
* [ ] Send out Social (tweet, blog, other)
* [ ] Send out customer communication (if any)
* [ ] Inform GCX that the new version is released (gcx@owncloud.com)
* [ ] Inform release-coordination@owncloud.com
* [ ] Ensure marketing is aware (marketing@owncloud.com)
* [ ] Take pride and celebrate!
* [x] Also update the testpilotcloud builds for that release version and make sure they show up on the download page
* [ ] Tell GCX to increment the minimum supported version for enterprise customers
* [ ] Check if minimum.supported.desktop.version (https://github.com/owncloud/core/blob/master/config/config.sample.php#L1152) needs to be updated in server

A few days after the release 
 * [ ] Update the updater script ```clientupdater.php``` (check the crash reporter if auto update is a good idea or we need a new release) https://github.com/owncloud/enterprise/pull/2246
* [ ] Execute announced deprecations. Disable builds for deprecated platforms. Update accordingly: https://doc.owncloud.org/server/latest/admin_manual/installation/system_requirements.html#desktop
* [ ] Increment version number in nightly builds. Special case: after the last release in a branch, jump forward to the 'next release branch'... That may mean, this is nightly is the same as edge then. 
https://github.com/owncloud/client/pull/6001

**Comment by guruz** [comment]
FYI @michaelstingl @jnweiger @SamuAlfageme

**Comment by guruz** [comment]
Changelog is up: https://github.com/owncloud/client/blob/2.3/ChangeLog

**Comment by SamuAlfageme** [comment]
@guruz updated w/ some more refs. Can't find the issues/PRs for: 

- https://github.com/owncloud/client/blob/2.3/ChangeLog#L10
- https://github.com/owncloud/client/blob/2.3/ChangeLog#L12

Could you ref. them?

**Comment by guruz** [comment]
Blocked by the APFS gold ticket (research) and on https://github.com/owncloud/enterprise/issues/2151

**Comment by SamuAlfageme** [comment]
### Blockers 
- [x] [macOS] Check file system unicode normalization is correct https://github.com/owncloud/client/issues/5650 
- [ ] "Open in browser" / "Open folder" doesn't work on some KDE distros: https://github.com/owncloud/enterprise/issues/2151

### 🆕 QA over **new**  (patch version specific) [Testing Scenarios 2.3.3](https://github.com/owncloud/client/blob/2.3/ChangeLog#L4-L14)

- [ ] Chunking NG: Don't use old chunking on new DAV endpoint (#5855)
- [ ] Selective Sync: Skip excluded folders when reading DB, don't let them show errors (#5772)
- [ ] Settings: Make window bigger so Qt version is always visible (#5760)
- [ ] Share links: Show warning that public link shares are public (#5786)
- [ ] Downloads: Re-trigger folder discovery on HTTP 404 (#5799)
- [ ]  SyncJournalDB: Don't use ._ as filename pattern if that does not work because of SMB storage settings (#5844)
- [ ]  SyncJournalDB: Log reason for sqlite3 opening errors
- [ ]  Switch Linux build also to Qt 5.6.2 (#5470)

--- 

### 💥 [Regression test on the whole client](https://github.com/owncloud/client/wiki/Testing-Scenarios)

- [ ] Installer/Uninstaller
- [ ] Setup
- [ ] Syncing
    - [ ] User stop syncing
    - [ ] Test resuming of uploads
    - [ ] Test resuming download
    - [ ] Modifying files when the sync is running
    - [ ] Test shared folder (*see Note below*)
- [ ] Network-related
- [ ] Crash Recovery
- [ ] Server interaction checks
- [ ] Upgrade (where applicable)
    - [ ] Upgrade from Previous Client Version 
    - [ ] Upgrade from previous server version
- [ ] Credential Management
    - [ ] First startup
    - [ ] Update
    - [ ] Password change, without URL change.
    - [ ] Password change, with URL change
    - [ ] Wrong password
    - [ ] Shibboleth
- [ ] Multiple folders
- [ ] Activity log (Including 2.3's https://github.com/owncloud/client/issues/5306)
- [ ] Quota
- [ ] Windows Office Files
- [ ] Big File modified during Upsync
- [ ] Command Line Client

---

### 📃 Notes:

**Comment by SamuAlfageme** [comment]
@guruz @michaelstingl all release blockers cleared out; I'm starting with the regression scenarios.

**Comment by guruz** [comment]
We have some builds in https://download.owncloud.com/desktop/testing/ and https://software.opensuse.org//download.html?project=isv%3AownCloud%3Acommunity%3Atesting&package=owncloud-client

We will publish them after testing

**Comment by guruz** [comment]
PR for website: https://github.com/owncloud/owncloud.org/pull/1250

**Comment by guruz** [comment]
Posting for central and mailing list: https://gist.github.com/guruz/29cb937de7d5fdeb360da75c7ae20b94

**Comment by SamuAlfageme** [comment]
@guruz other than https://github.com/owncloud/client/issues/5949 I found no issues on the regression tests. We can announce the RC1 now 👍

**Comment by guruz** [comment]
Waiting for deployment of https://github.com/owncloud/owncloud.org/pull/1250 then announcing

**Comment by guruz** [comment]
https://central.owncloud.org/t/desktop-sync-client-2-3-3-rc1-release-candidate-released/8967

**Comment by guruz** [comment]
Linking https://github.com/owncloud/enterprise/issues/2151

**Comment by guruz** [comment]
Starting build of rc2 with latest changes of @jnweiger in OBS

**Comment by guruz** [comment]
rc2 @ https://download.owncloud.com/desktop/testing/   https://software.opensuse.org//download.html?project=isv%3AownCloud%3Acommunity%3Atesting&package=owncloud-client

**Comment by guruz** [comment]
rc2 PR @ https://github.com/owncloud/owncloud.org/pull/1256

**Comment by jnweiger** [comment]
Triggered 2.3.3 final builds for ownCloud-client and testpilotcloud-client:
* https://jenkins.int.owncloud.com/view/client/job/official-client-trigger/244/
* https://jenkins.int.owncloud.com/view/client/job/official-client-trigger/245/

That should push the linux builds into their :testing projects.

TODO:
* [ ]  I'll have to double check if sources, win and mac builds end up in the proper location 
* [ ] find out how to sign the sources. @guruz your help needed here, I am afraid.
* [ ] create one monster submitrequest  that moves from :testing to the main project.

**Comment by jnweiger** [comment]
owncloud.org website updates for staging https://github.com/owncloud/owncloud.org/pull/1273
@michaelstingl  Please review the changelog and double check the deprecation warnings.

**Comment by guruz** [comment]
Downloaded and installed macOS and Windows versions, they work for me.
I didn't check Linux

**Comment by jnweiger** [comment]
I am doing one more rebuild in OBS: renaming all xUbuntu* to Ubuntu* -- that is how it was with 2.3.2 -- we don't want to break update repos.

**Comment by jnweiger** [comment]
Rebuilds done. All fine. Let's publish!

**Comment by guruz** [comment]
@jnweiger Cool! Any way to redirect the Qt562 OBS repo somehow to make people get automated update there? I think @dragotin mentioned that..

**Comment by jnweiger** [comment]
Hmm. Not sure what @dragotin wanted to achieve. We'll update the qt562 libs together with the clients anyway.

**Comment by glannes31** [comment]
Hello , 2.3.3 is not publish on owncloud.org . A problem with that ?

**Comment by SamuAlfageme** [comment]
@glannes31 you're right, looks like https://staging.owncloud.org/install/#install-clients hasn't gone live yet - PR with the changes was merged in https://github.com/owncloud/owncloud.org/pull/1273. I'll ask the admins around.

**Comment by jnweiger** [comment]
2.3.3 is live:
* OBS pushed
* https://owncloud.org/install/#install-clients pushed
* announcement on https://central.owncloud.org/t/desktop-sync-client-2-3-3-released/8967

**Comment by jnweiger** [comment]
update the updater: https://github.com/owncloud/enterprise/pull/2246

**Comment by guruz** [comment]
Closing issue.
We still have pending things in milestone: https://github.com/owncloud/client/milestone/41

**Comment by tripplex95** [comment]
cant change the "connect to ownCloud on the application windows and connect to ownCloud server"
