### ISSUE TITLE
[Meta] "Sync Exclusion" Compilation  

### ISSUE THREAD

**Issue by SamuAlfageme** [owncloud/client#6182]
- [x] Regex exclude patterns
    - https://github.com/owncloud/client/issues/6181
- [x] Interpret ".gitignores":
    - https://github.com/owncloud/client/issues/2097
    - https://github.com/owncloud/client/issues/4054
- [ ] Per-directory folder exclusions
    - https://github.com/owncloud/client/issues/1558 
- [ ] Logging / exclude categories:
    - https://github.com/owncloud/client/issues/1940
- [ ] Hierarchy: https://github.com/owncloud/client/issues/5754
- [ ] Comming from server (blacklisted files) - Yet another dinamic config option comming from the server to modify client's behavior:
    - https://github.com/owncloud/client/issues/434 
    - https://github.com/owncloud/client/issues/1369
- [ ] Size ignore: https://github.com/owncloud/client/issues/4109 (similar to 'do not download files larger than...')
- [ ] Exclussion from top level paths: 
    - https://github.com/owncloud/client/issues/4150
    - https://github.com/owncloud/client/issues/4344
    - related: https://github.com/owncloud/client/issues/3664 & https://github.com/owncloud/client/issues/3632

**Comment by ckamm** [comment]
Also relevant: Description of current matching and suggestions for improvment: https://github.com/owncloud/client/issues/5275
