### ISSUE TITLE
[Meta] "ownCloud" context menu options Compilation

### ISSUE THREAD

**Issue by SamuAlfageme** [owncloud/client#6292]
- [x] Add "Open file/folder in browser" to shell extension context menu - https://github.com/owncloud/client/issues/5903

## Dynamically disable/grey-out the context menu dropdown
- [x] When folder is not ready yet: https://github.com/owncloud/client/issues/4608
- [x] When sharing is disabled in server (globally) or file (`oc:permissions`): https://github.com/owncloud/client/issues/4205
- [ ] When the client is offline/server unreacheable (just the "Share" entry, i.e. mechanism to generate Private link based on DB contents is offline-friendly already)

## Additional tickets
- [ ] [Discussion] Multi-account locally shared folders (https://github.com/owncloud/client/issues/3764) - Add an intermediate "account" dropdown. https://github.com/owncloud/client/issues/5462
- [ ] [Discussion] Enable a `Move to ownCloud > account` outside the local sync folder? - Was disabled in: https://github.com/owncloud/client/issues/2732 
- [ ] Different actions based on the file/folder permissions: https://github.com/owncloud/client/issues/6252
- [ ] "Public link" share shortcut: https://github.com/owncloud/client/issues/6356

**Comment by mmattel** [comment]
Maybe to add under additional tickets: https://github.com/owncloud/client/issues/6202
This is something where core is involved, but it affects the client
