### ISSUE TITLE
Improved notifications

### ISSUE THREAD

**Issue by TheOneRing** [owncloud/client#7552]
- [ ] Improve existing notification wording
- [ ] Use more notifications
- [ ] Add actions buttons to the Mac and Linux notification implementation
- [ ] Implement Windows Toast notifications
- [ ] Implement fallback solution

### Related

- https://github.com/owncloud/client/issues/4697
- https://github.com/owncloud/client/issues/4802
- https://github.com/owncloud/client/issues/4841
- https://github.com/owncloud/client/issues/5493
- https://github.com/owncloud/client/issues/5587
- https://github.com/owncloud/client/issues/6443
- **Windows** specific
  - https://github.com/owncloud/client/issues/3725
- **macOS** specific
  - https://github.com/owncloud/client/issues/4410
- Also check
  - https://github.com/owncloud/client/issues/4787 (server involved?)

**Comment by TheOneRing** [comment]
@michaelstingl @guruz what do you think?

**Comment by guruz** [comment]
Feel free to do it :-)

Please also check if you can assign yourself individual existing issues instead https://github.com/owncloud/client/search?q=notifications&state=open&type=Issues
