### ISSUE TITLE
Community Desktop Client 2.6.1

### ISSUE THREAD

**Issue by HanaGemela** [owncloud/client#7651]
### Create Changelog

* [x] DEV: Update [ChangeLog](https://handbook.owncloud.com/release_processes/client/change_log.html)
* [x] QA: 1h later check [ChangeLog on website](https://owncloud.org/changelog/desktop-client/)

### Prerequisites

* [x] QA: Update [Test Plans](https://handbook.owncloud.com/release_processes/client/testlink.html) 
* [x] QA: Update [documentation](https://handbook.owncloud.com/release_processes/client/documentation.html) -  https://github.com/owncloud/client/issues/7632
* [x] QA: Check the translations coming from [Transifex](https://handbook.owncloud.com/release_processes/client/miscellaneous.html#transifex)
* [x] DEV: Check [dependencies](https://handbook.owncloud.com/release_processes/client/dependencies.html) for updates
* [x] DEV: Branch off a sprint branch called e.g. `sprint-1`

### Sprint Build

* [x] QA: Create [builds](https://handbook.owncloud.com/release_processes/client/build.html#sprint-build) for theme 'ownCloud' and 'testpilotcloud'
* [x] QA: Check if `*tar.xz.asc` files are [here](https://download.owncloud.com/desktop/testing). If not follow the [instructions](https://github.com/owncloud/enterprise/wiki/Desktop-Signing-Knowledge)
* [ ] QA: Inform [stakeholders](https://handbook.owncloud.com/release_processes/client/marketing.html#inform-stakeholders-after-successful-sprint-build)

#### DEV QA
* [ ] DEV: [Smoke test](https://handbook.owncloud.com/release_processes/client/manual_tests.html#dev-smoke-test)
* [ ] DEV: Run [automated tests](https://handbook.owncloud.com/release_processes/client/automated_tests.html)
#### BTR QA
* [x] QA: [Antivirus scan](https://handbook.owncloud.com/release_processes/client/virus.html)
* [x] QA: Changelog testing
* [x] QA: [Regression test](https://handbook.owncloud.com/release_processes/client/manual_tests.html#regression-test)

### After QA Approval

* [x] DEV: Remove git suffix in `MIRALL_VERSION_SUFFIX` in [`VERSION.cmake`](https://handbook.owncloud.com/release_processes/client/branch.html#version-cmake)
* [x] DEV: On sprint branch create a [signed tag](https://handbook.owncloud.com/release_processes/client/build.html#client-repository) v2.6.1
* [x] DEV: Delete the sprint branch
* [x] DEV: Create the same tag on branch 2.6 of [_client-plugin-vfs-win_](https://handbook.owncloud.com/release_processes/client/build.html#client-plugin-vfs-win)
* [x] DEV: Create the same tag on branch 2.6 of [_wip-msi_](https://handbook.owncloud.com/release_processes/client/build.html#wip-msi)
* [x] DEV: Create same tag for [Windows toolchain](https://handbook.owncloud.com/release_processes/client/build.html#windows-toolchain)
* [x] DEV: Create same tag (actually a symlink) for [macOS toolchain](https://handbook.owncloud.com/release_processes/client/build.html#macos-toolchain)

### Final Rebuild

* [x] QA: Change the date in `ChangeLog` to the date of creating the tag 
* [x] QA: Bump `MIRALL_VERSION_PATCH` in [`VERSION.cmake`](https://handbook.owncloud.com/release_processes/client/branch.html#patch-release)
* [x] QA: Adjust [Linux Templates](https://handbook.owncloud.com/release_processes/client/branch.html#linux-templates) to support the next patch release version (e.g. 2.6.2)
* [x] QA: Run [client-trigger](https://handbook.owncloud.com/release_processes/client/build.html#final-build) 
* [x] QA: Ping marketing to do their [actions](https://handbook.owncloud.com/release_processes/client/marketing.html#marketing)
* [x] QA: [Backup](https://handbook.owncloud.com/release_processes/client/desktop.html#backup-the-previous-desktop-project) the desktop project in OBS to _desktop:client-2.6.0_
* [x] QA: [Disable publishing](https://handbook.owncloud.com/release_processes/client/desktop.html#disable-publishing-and-on-project-isvownclouddesktop) on project _isv:ownCloud:desktop_ in OBS
* [x] QA: Copy from [testing to released](https://handbook.owncloud.com/release_processes/client/desktop.html#copy-from-testing-to-released-in-obs) in OBS
* [x] QA: Re-enable [OBS publishing](https://handbook.owncloud.com/release_processes/client/desktop.html#re-enable-obs-publishing)
* [x] QA: [Copy](https://handbook.owncloud.com/release_processes/client/desktop.html#copy-from-testing-to-stable) builds from ```testing``` to ```stable```
* [x] QA: Create [a (draft) release](https://github.com/owncloud/client/releases) with Download links - save as a draft until smoke tested
* [x] QA: Create a new release issue for a branded release if needed
* [ ] QA: Give [heads-up](https://handbook.owncloud.com/release_processes/client/marketing.html#heads-up-before-the-final-release) before the final release 

### Final QA

* [x] QA: [Smoke test](https://handbook.owncloud.com/release_processes/client/manual_tests.html#smoke-test)
* [x] QA: Check if [GitHub download links](https://github.com/owncloud/client/releases) point to correct location
* [x] QA: Publish the release in GitHub
* [ ] QA: Check [minimum.supported.desktop.version](https://github.com/owncloud/core/blob/master/config/config.sample.php#L1367) on the server https://github.com/owncloud/core/pull/36796

### Communicate the Availability

* [x] QA: Announce on [central](https://handbook.owncloud.com/release_processes/client/marketing.html#central)
* [x] QA: Inform [stakeholders](https://handbook.owncloud.com/release_processes/client/marketing.html#inform-stakeholders-about-final)
* [x] QA: Inform [packagers](https://handbook.owncloud.com/release_processes/client/marketing.html#packagers) - ping @dragotin (openSUSE)
* [x] QA: Inform [community mailing lists](https://handbook.owncloud.com/release_processes/client/marketing.html#inform-community-mailing-lists) - ended up as spam, asked sysadmin

### Final Infrastructure Check

* [x] QA/DEV: Update [stable channel](https://handbook.owncloud.com/release_processes/client/miscellaneous.html#update-the-updater) in the owncloud hosted auto updater
* [x] QA/DEV: Ensure that the [client patch release template](https://github.com/owncloud/client/master/.github/release_template_patch.md) is up to date
* [ ] QA: Update [supported platforms](https://handbook.owncloud.com/release_processes/client/supported_platforms.html) - https://github.com/owncloud/client/issues/7633

### A Few Days After the Release

* [x] DEV: Check the [crash reporter](https://handbook.owncloud.com/release_processes/client/desktop.html#crash-reporter) for bad/frequent crashes - https://github.com/owncloud/client/issues/7722

**Comment by HanaGemela** [comment]
Sprint 01 build:
osx: https://jenkins.int.owncloud.com/job/client-osx/12882/
Linux: https://jenkins.int.owncloud.com/job/client-linux-obs/1899/console
Windows: https://jenkins.int.owncloud.com/job/client-win32-msvc-msi/12862/

**Comment by jnweiger** [comment]
Test install Linux build 1909:```
|ubuntu:18.04|01-owncloudcmd_version.sh|        ownCloud version 2.6.1sprint1 (build 1909)
|ubuntu:18.10|01-owncloudcmd_version.sh|        ownCloud version 2.6.1sprint1 (build 1909)
|ubuntu:19.04|01-owncloudcmd_version.sh|        ownCloud version 2.6.1sprint1 (build 1909)
|ubuntu:19.10|01-owncloudcmd_version.sh|        ownCloud version 2.6.1sprint1 (build 1909)
|debian:8|01-owncloudcmd_version.sh|    qt.network.ssl: QSslSocket: cannot resolve X509_STORE_CTX_get0_store
|debian:8|01-owncloudcmd_version.sh|    ownCloud version 2.6.1sprint1 (build 1909)
|debian:9|01-owncloudcmd_version.sh|    ownCloud version 2.6.1sprint1 (build 1909)
|debian:10|01-owncloudcmd_version.sh|   ownCloud version 2.6.1sprint1 (build 1909)
|fedora:27|01-owncloudcmd_version.sh|   ownCloud version 2.6.1sprint1 (build 1909)
|fedora:28|01-owncloudcmd_version.sh|   ownCloud version 2.6.1sprint1 (build 1909)
|fedora:29|01-owncloudcmd_version.sh|   ownCloud version 2.6.1sprint1 (build 1909)
|fedora:30|01-owncloudcmd_version.sh|   ownCloud version 2.6.1sprint1 (build 1909)
|fedora:31|01-owncloudcmd_version.sh|   ownCloud version 2.6.1sprint1 (build 1909)
|centos:6|01-owncloudcmd_version.sh|    qt.network.ssl: QSslSocket: cannot resolve X509_STORE_CTX_get0_store
|centos:6|01-owncloudcmd_version.sh|    ownCloud version 2.6.1sprint1 (build 1909)
|centos:7|01-owncloudcmd_version.sh|    ownCloud version 2.6.1sprint1 (build 1909)
|centos:8|01-owncloudcmd_version.sh|    ownCloud version 2.6.1sprint1 (build 1909)
|opensuse/leap:42.3|01-owncloudcmd_version.sh|  ownCloud version 2.6.1sprint1 (build 1909)
|opensuse/leap:15.1|01-owncloudcmd_version.sh|  ownCloud version 2.6.1sprint1 (build 1909)
|ubuntu:18.04|find-cloud-provides-ini.sh|       ls: cannot access '/usr/share/cloud-providers/*.ini': No such file or directory
|ubuntu:18.10|find-cloud-provides-ini.sh|       ls: cannot access '/usr/share/cloud-providers/*.ini': No such file or directory
|ubuntu:19.04|find-cloud-provides-ini.sh|       -rw-r--r-- 1 root root 102 Dec 19 13:42 /usr/share/cloud-providers/com.owncloud.desktopclient.ini
|ubuntu:19.10|find-cloud-provides-ini.sh|       -rw-r--r-- 1 root root 102 Dec 19 13:43 /usr/share/cloud-providers/com.owncloud.desktopclient.ini
|debian:8|find-cloud-provides-ini.sh|   ls: cannot access /usr/share/cloud-providers/*.ini: No such file or directory
|debian:9|find-cloud-provides-ini.sh|   ls: cannot access '/usr/share/cloud-providers/*.ini': No such file or directory
|debian:10|find-cloud-provides-ini.sh|  -rw-r--r-- 1 root root 102 Dec 19 13:16 /usr/share/cloud-providers/com.owncloud.desktopclient.ini
|fedora:27|find-cloud-provides-ini.sh|  ls: cannot access '/usr/share/cloud-providers/*.ini': No such file or directory
|fedora:28|find-cloud-provides-ini.sh|  ls: cannot access '/usr/share/cloud-providers/*.ini': No such file or directory
|fedora:29|find-cloud-provides-ini.sh|  ls: cannot access '/usr/share/cloud-providers/*.ini': No such file or directory
|fedora:30|find-cloud-provides-ini.sh|  ls: cannot access '/usr/share/cloud-providers/*.ini': No such file or directory
|fedora:31|find-cloud-provides-ini.sh|  ls: cannot access '/usr/share/cloud-providers/*.ini': No such file or directory
|centos:6|find-cloud-provides-ini.sh|   ls: cannot access /usr/share/cloud-providers/*.ini: No such file or directory
|centos:7|find-cloud-provides-ini.sh|   ls: cannot access /usr/share/cloud-providers/*.ini: No such file or directory
|centos:8|find-cloud-provides-ini.sh|   ls: cannot access '/usr/share/cloud-providers/*.ini': No such file or directory
|opensuse/leap:42.3|find-cloud-provides-ini.sh| ls: cannot access '/usr/share/cloud-providers/*.ini': No such file or directory
|opensuse/leap:15.1|find-cloud-provides-ini.sh| ls: cannot access '/usr/share/cloud-providers/*.ini': No such file or directory
|opensuse/leap:15.2|find-cloud-provides-ini.sh| ls: cannot access '/usr/share/cloud-providers/*.ini': No such file or directory
|ubuntu:18.04|find-sync-exclude.lst.sh| -rw-r--r-- 1 root root 418 Dec 19 13:12 /etc/ownCloud/sync-exclude.lst
|ubuntu:18.10|find-sync-exclude.lst.sh| -rw-r--r-- 1 root root 418 Dec 19 13:12 /etc/ownCloud/sync-exclude.lst
|ubuntu:19.04|find-sync-exclude.lst.sh| -rw-r--r-- 1 root root 418 Dec 19 13:12 /etc/ownCloud/sync-exclude.lst
|ubuntu:19.10|find-sync-exclude.lst.sh| -rw-r--r-- 1 root root 418 Dec 19 13:12 /etc/ownCloud/sync-exclude.lst
|debian:8|find-sync-exclude.lst.sh|     -rw-r--r-- 1 root root 418 Dec 19 13:12 /etc/ownCloud/sync-exclude.lst
|debian:9|find-sync-exclude.lst.sh|     -rw-r--r-- 1 root root 418 Dec 19 13:12 /etc/ownCloud/sync-exclude.lst
|debian:10|find-sync-exclude.lst.sh|    -rw-r--r-- 1 root root 418 Dec 19 13:12 /etc/ownCloud/sync-exclude.lst
|fedora:27|find-sync-exclude.lst.sh|    -rw-r--r-- 1 root root 418 Dec 19 13:12 /etc/ownCloud/sync-exclude.lst
|fedora:28|find-sync-exclude.lst.sh|    -rw-r--r-- 1 root root 418 Dec 19 13:12 /etc/ownCloud/sync-exclude.lst
|fedora:29|find-sync-exclude.lst.sh|    -rw-r--r-- 1 root root 418 Dec 19 13:12 /etc/ownCloud/sync-exclude.lst
|fedora:30|find-sync-exclude.lst.sh|    -rw-r--r-- 1 root root 418 Dec 19 13:12 /etc/ownCloud/sync-exclude.lst
|fedora:31|find-sync-exclude.lst.sh|    -rw-r--r-- 1 root root 418 Dec 19 13:12 /etc/ownCloud/sync-exclude.lst
|centos:6|find-sync-exclude.lst.sh|     -rw-r--r-- 1 root root 418 Dec 19 13:12 /etc/ownCloud/sync-exclude.lst
|centos:7|find-sync-exclude.lst.sh|     -rw-r--r-- 1 root root 418 Dec 19 13:12 /etc/ownCloud/sync-exclude.lst
|centos:8|find-sync-exclude.lst.sh|     -rw-r--r-- 1 root root 418 Dec 19 13:12 /etc/ownCloud/sync-exclude.lst
|opensuse/leap:42.3|find-sync-exclude.lst.sh|   -rw-r--r-- 1 root root 418 Dec 19 13:12 /etc/ownCloud/sync-exclude.lst
|opensuse/leap:15.1|find-sync-exclude.lst.sh|   -rw-r--r-- 1 root root 418 Dec 19 13:12 /etc/ownCloud/sync-exclude.lst
|opensuse/leap:15.2|find-sync-exclude.lst.sh|   ls: cannot access '/etc/*/sync-exclude.lst': No such file or directory
```
Looks good to me! (finally here with 1909, the original build 1899 had many packaging issues)

**Comment by HanaGemela** [comment]
Sprint 2 build available in https://download.owncloud.com/desktop/testing/

**Comment by HanaGemela** [comment]
Changelog: https://github.com/owncloud/client/blob/sprint-2/ChangeLog

**Comment by HanaGemela** [comment]
Changes:
* [ ] GUI: Change the display name to "server (user name)", show the full text in the tooltip (#6728)
* [ ] GUI: Add quit button to the settings dialog (#7547)
* [ ] GUI: Show a warning that proxy settings do not apply to localhost (#7169)
* [ ] CLI: Make it possible to show settings/quit by command line invocation (#7018, #7547)
* [ ] Linux:  Add action to Desktop file to show settings, quit the client (#7018, #7547)

Bugfixes:
* [ ] Sync: Correctly sync files on Windows after they got unlocked (owncloud/enterprise#3609)
* [ ] Log: Message priority wasn't handled correctly so the console log was flooded(#7453)
* [ ] Vfs: Do not overwrite existing files by placeholder (#7557,  #7556)
* [ ] Discovery:  Allow more HTTP error code to be treated as ignored dir (#7586)
* [ ] GUI: Limit the clickable region of the 'add folder' button (#7326)
* [ ] GUI: Don't show the "All files deleted" popup when unselecting everything with selective sync (#7337)
* [ ] GUI: Don't put a too big icon in about dialog (#7574)
* [ ] Shell Integration: Don't assume read-only folder when permissions are not known (#7330)
* [ ] Sync: Temporary disable http2 support by default again (#7610)
* [ ] Windows Installer: Remember install location on auto update (#7580)

**Comment by jnweiger** [comment]
Sprint2 linux install test results:
```
root@client-linux-install-test-juergen:~# bash tests.sh
|ubuntu:18.04|01-owncloudcmd_version.sh|        ownCloud version 2.6.1sprint2 (build 1994)
|ubuntu:18.10|01-owncloudcmd_version.sh|        ownCloud version 2.6.1sprint2 (build 1994)
|ubuntu:19.04|01-owncloudcmd_version.sh|        ownCloud version 2.6.1sprint2 (build 1994)
|ubuntu:19.10|01-owncloudcmd_version.sh|        ownCloud version 2.6.1sprint2 (build 1994)
|debian:8|01-owncloudcmd_version.sh|    ownCloud version 2.6.1sprint2 (build 1994)
|debian:9|01-owncloudcmd_version.sh|    ownCloud version 2.6.1sprint2 (build 1994)
|debian:10|01-owncloudcmd_version.sh|   ownCloud version 2.6.1sprint2 (build 1994)
|fedora:27|01-owncloudcmd_version.sh|   ownCloud version 2.6.1sprint2 (build 1994)
|fedora:28|01-owncloudcmd_version.sh|   ownCloud version 2.6.1sprint2 (build 1994)
|fedora:29|01-owncloudcmd_version.sh|   ownCloud version 2.6.1sprint2 (build 1994)
|fedora:30|01-owncloudcmd_version.sh|   ownCloud version 2.6.1sprint2 (build 1994)
|fedora:31|01-owncloudcmd_version.sh|   ownCloud version 2.6.1sprint2 (build 1994)
|centos:6|01-owncloudcmd_version.sh|    ownCloud version 2.6.1sprint2 (build 1994)
|centos:7|01-owncloudcmd_version.sh|    ownCloud version 2.6.1sprint2 (build 1994)
|centos:8|01-owncloudcmd_version.sh|    ownCloud version 2.6.1sprint2 (build 1994)
|opensuse/leap:42.3|01-owncloudcmd_version.sh|  ownCloud version 2.6.1sprint2 (build 1994)
|opensuse/leap:15.1|01-owncloudcmd_version.sh|  ownCloud version 2.6.1sprint2 (build 1994)
|opensuse/leap:15.2|01-owncloudcmd_version.sh|  ownCloud version 2.6.1sprint2 (build 1994)
```

OK.

**Comment by jnweiger** [comment]
#7556 and #7557 are currently at milestone 2.6.2 -- they should not block here.

**Comment by jnweiger** [comment]
#7556 is closed fixed now! Keep it in the changelog of 2.6.1 :-)

**Comment by HanaGemela** [comment]
Regression test done [Regression test 2.6.1 Sprint2.pdf](https://github.com/owncloud/client/files/4072285/Regression.test.2.6.1.Sprint2.pdf)

I've run into https://github.com/owncloud/client/issues/7570 again, other than that the test passed

**Comment by SpacyNG** [comment]
From my experience, #7576 is also fixed. Running Ubuntu 19.10 with daily built 2000.

**Comment by jnweiger** [comment]
We reached the point of no return: I just tagged sprint-2 with v2.6.1

```
git verify-tag v2.6.1 -v -v
object 6793f774adcd4beff46923ff7186ff1a9b6ec47c
type commit
tag v2.6.1
tagger Juergen Weigert <jnweiger@gmail.com> 1579267473 +0100

Create v2.6.1 tag
gpg: Signature made Fri 17 Jan 2020 02:24:33 PM CET
gpg:                using RSA key F05F7DD7953A07DF36579DAA498C45EBE94E7B37
gpg: Good signature from "ownCloud Client Team (Signing Key) <info@owncloud.com>" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: F05F 7DD7 953A 07DF 3657  9DAA 498C 45EB E94E 7B37

**Comment by jnweiger** [comment]
Seems, it is currently not possible to tag the Windows toolchain:
```
docker pull registry.owncloud.com/client/windows:2.6
Error response from daemon: Get https://registry.owncloud.com/v2/client/windows/manifests/2.6: received unexpected HTTP status: 500 Internal Server Error
```

**Comment by TheOneRing** [comment]
> Seems, it is currently not possible to tag the Windows toolchain:
> 
> ```
> docker pull registry.owncloud.com/client/windows:2.6
> Error response from daemon: Get https://registry.owncloud.com/v2/client/windows/manifests/2.6: received unexpected HTTP status: 500 Internal Server Error
> ```

Hm I think we don't push the imaged due to their size...
@dschmidt could you tag it on the server?

**Comment by jnweiger** [comment]
Done locally on 159.69.157.76
```
PS E:\tmp> docker images
REPOSITORY                                  TAG                              IMAGE ID            CREATED             SIZE 
registry.owncloud.com/client/windows-base   latest                           9105e44f896b        2 months ago        24.8GB 
registry.owncloud.com/client/windows        2.6                              71188d3421cd        3 months ago        30.5GB 
registry.owncloud.com/client/windows        2.7                              71188d3421cd        3 months ago        30.5GB 
registry.owncloud.com/client/windows        v2.6.0                           71188d3421cd        3 months ago        30.5GB 
registry.owncloud.com/client/windows        v2.6.1                           71188d3421cd        3 months ago        30.5GB 
```

**Comment by jnweiger** [comment]
Added macOS toolchain: symlinks for v2.6.1 (same place and same targets as v2.6.0) on
* ownCloud@207.254.28.42
* builder@10.90.4.91
* builder@10.90.4.93

**Comment by jnweiger** [comment]
Yesterday's final builds for 2.6.1 failed for Windows and Mac, but succeeded for Linux.
https://jenkins.int.owncloud.com/view/client/job/client-trigger/4055/

Linux installation test results look great:
```
|repourl| http://download.opensuse.org/repositories/isv:/ownCloud:/desktop:/testing
|package| owncloud-client
|ubuntu:18.04|01-owncloudcmd_version.sh|        ownCloud version 2.6.1 (build 2038)
|ubuntu:18.04|01-owncloudcmd_version.sh|        Using 'OpenSSL 1.1.1  11 Sep 2018'
|ubuntu:18.10|01-owncloudcmd_version.sh|        ownCloud version 2.6.1 (build 2038)
|ubuntu:18.10|01-owncloudcmd_version.sh|        Using 'OpenSSL 1.1.1  11 Sep 2018'
|ubuntu:19.04|01-owncloudcmd_version.sh|        ownCloud version 2.6.1 (build 2038)
|ubuntu:19.04|01-owncloudcmd_version.sh|        Using 'OpenSSL 1.1.1b  26 Feb 2019'
|ubuntu:19.10|01-owncloudcmd_version.sh|        ownCloud version 2.6.1 (build 2038)
|ubuntu:19.10|01-owncloudcmd_version.sh|        Using 'OpenSSL 1.1.1c  28 May 2019'
|debian:8|01-owncloudcmd_version.sh|            ownCloud version 2.6.1 (build 2038)
|debian:8|01-owncloudcmd_version.sh|            Using 'OpenSSL 1.0.1t  3 May 2016'
|debian:9|01-owncloudcmd_version.sh|            ownCloud version 2.6.1 (build 2038)
|debian:9|01-owncloudcmd_version.sh|            Using 'OpenSSL 1.1.0l  10 Sep 2019'
|debian:10|01-owncloudcmd_version.sh|           ownCloud version 2.6.1 (build 2038)
|debian:10|01-owncloudcmd_version.sh|           Using 'OpenSSL 1.1.1d  10 Sep 2019'
|fedora:27|01-owncloudcmd_version.sh|           ownCloud version 2.6.1 (build 2038)
|fedora:27|01-owncloudcmd_version.sh|           Using 'OpenSSL 1.0.2o-fips  27 Mar 2018'
|fedora:28|01-owncloudcmd_version.sh|           ownCloud version 2.6.1 (build 2038)
|fedora:28|01-owncloudcmd_version.sh|           Using 'OpenSSL 1.0.2o-fips  27 Mar 2018'
|fedora:29|01-owncloudcmd_version.sh|           ownCloud version 2.6.1 (build 2038)
|fedora:29|01-owncloudcmd_version.sh|           Using 'OpenSSL 1.1.1b FIPS  26 Feb 2019'
|fedora:30|01-owncloudcmd_version.sh|           ownCloud version 2.6.1 (build 2038)
|fedora:30|01-owncloudcmd_version.sh|           Using 'OpenSSL 1.1.1d FIPS  10 Sep 2019'
|fedora:31|01-owncloudcmd_version.sh|           ownCloud version 2.6.1 (build 2038)
|fedora:31|01-owncloudcmd_version.sh|           Using 'OpenSSL 1.1.1d FIPS  10 Sep 2019'
|centos:6|01-owncloudcmd_version.sh|            ownCloud version 2.6.1 (build 2038)
|centos:6|01-owncloudcmd_version.sh|            Using 'OpenSSL 1.0.1e-fips 11 Feb 2013'
|centos:7|01-owncloudcmd_version.sh|            ownCloud version 2.6.1 (build 2038)
|centos:7|01-owncloudcmd_version.sh|            Using 'OpenSSL 1.0.2k-fips  26 Jan 2017'
|centos:8|01-owncloudcmd_version.sh|            ownCloud version 2.6.1 (build 2038)
|centos:8|01-owncloudcmd_version.sh|            Using 'OpenSSL 1.1.1 FIPS  11 Sep 2018'
|opensuse/leap:42.3|01-owncloudcmd_version.sh|  ownCloud version 2.6.1 (build 2038)
|opensuse/leap:42.3|01-owncloudcmd_version.sh|  Using 'OpenSSL 1.0.2j-fips  26 Sep 2016'
|opensuse/leap:15.1|01-owncloudcmd_version.sh|  ownCloud version 2.6.1 (build 2038)
|opensuse/leap:15.1|01-owncloudcmd_version.sh|  Using 'OpenSSL 1.1.0i-fips  14 Aug 2018'
|opensuse/leap:15.2|01-owncloudcmd_version.sh|  ownCloud version 2.6.1 (build 2038)
|opensuse/leap:15.2|01-owncloudcmd_version.sh|  Using 'OpenSSL 1.1.1d  10 Sep 2019'
```

Upon special request, this report includes ssl versions :-)
Linux clients rely on system ssl, unlike win or mac, where we bring our own ssl.

**Comment by jnweiger** [comment]
Results from Linux client install test

```
|repourl| http://download.opensuse.org/repositories/isv:/ownCloud:/desktop:/testing
|package| owncloud-client
|ubuntu:18.04|01-owncloudcmd_version.sh|	ownCloud version 2.6.1 (build 2071)
|ubuntu:18.04|01-owncloudcmd_version.sh|	Using 'OpenSSL 1.1.1  11 Sep 2018'
|ubuntu:18.10|01-owncloudcmd_version.sh|	ownCloud version 2.6.1 (build 2071)
|ubuntu:18.10|01-owncloudcmd_version.sh|	Using 'OpenSSL 1.1.1  11 Sep 2018'
|ubuntu:19.04|01-owncloudcmd_version.sh|	ownCloud version 2.6.1 (build 2071)
|ubuntu:19.04|01-owncloudcmd_version.sh|	Using 'OpenSSL 1.1.1b  26 Feb 2019'
|ubuntu:19.10|01-owncloudcmd_version.sh|	ownCloud version 2.6.1 (build 2071)
|ubuntu:19.10|01-owncloudcmd_version.sh|	Using 'OpenSSL 1.1.1c  28 May 2019'
|debian:8|01-owncloudcmd_version.sh|	ownCloud version 2.6.1 (build 2071)
|debian:8|01-owncloudcmd_version.sh|	Using 'OpenSSL 1.0.1t  3 May 2016'
|debian:9|01-owncloudcmd_version.sh|	ownCloud version 2.6.1 (build 2071)
|debian:9|01-owncloudcmd_version.sh|	Using 'OpenSSL 1.1.0l  10 Sep 2019'
|debian:10|01-owncloudcmd_version.sh|	ownCloud version 2.6.1 (build 2071)
|debian:10|01-owncloudcmd_version.sh|	Using 'OpenSSL 1.1.1d  10 Sep 2019'
|fedora:27|01-owncloudcmd_version.sh|	ownCloud version 2.6.1 (build 2071)
|fedora:27|01-owncloudcmd_version.sh|	Using 'OpenSSL 1.0.2o-fips  27 Mar 2018'
|fedora:28|01-owncloudcmd_version.sh|	ownCloud version 2.6.1 (build 2071)
|fedora:28|01-owncloudcmd_version.sh|	Using 'OpenSSL 1.0.2o-fips  27 Mar 2018'
|fedora:29|01-owncloudcmd_version.sh|	ownCloud version 2.6.1 (build 2071)
|fedora:29|01-owncloudcmd_version.sh|	Using 'OpenSSL 1.1.1b FIPS  26 Feb 2019'
|fedora:30|01-owncloudcmd_version.sh|	ownCloud version 2.6.1 (build 2071)
|fedora:30|01-owncloudcmd_version.sh|	Using 'OpenSSL 1.1.1d FIPS  10 Sep 2019'
|fedora:31|01-owncloudcmd_version.sh|	ownCloud version 2.6.1 (build 2071)
|fedora:31|01-owncloudcmd_version.sh|	Using 'OpenSSL 1.1.1d FIPS  10 Sep 2019'
|centos:6|01-owncloudcmd_version.sh|	ownCloud version 2.6.1 (build 2071)
|centos:6|01-owncloudcmd_version.sh|	Using 'OpenSSL 1.0.1e-fips 11 Feb 2013'
|centos:7|01-owncloudcmd_version.sh|	ownCloud version 2.6.1 (build 2071)
|centos:7|01-owncloudcmd_version.sh|	Using 'OpenSSL 1.0.2k-fips  26 Jan 2017'
|centos:8|01-owncloudcmd_version.sh|	ownCloud version 2.6.1 (build 2071)
|centos:8|01-owncloudcmd_version.sh|	Using 'OpenSSL 1.1.1c FIPS  28 May 2019'
|opensuse/leap:42.3|01-owncloudcmd_version.sh|	ownCloud version 2.6.1 (build 2071)
|opensuse/leap:42.3|01-owncloudcmd_version.sh|	Using 'OpenSSL 1.0.2j-fips  26 Sep 2016'
|opensuse/leap:15.1|01-owncloudcmd_version.sh|	ownCloud version 2.6.1 (build 2071)
|opensuse/leap:15.1|01-owncloudcmd_version.sh|	Using 'OpenSSL 1.1.0i-fips  14 Aug 2018'
|opensuse/leap:15.2|01-owncloudcmd_version.sh|	ownCloud version 2.6.1 (build 2071)
|opensuse/leap:15.2|01-owncloudcmd_version.sh|	Using 'OpenSSL 1.1.1d  10 Sep 2019'
|ubuntu:18.04|02-find-key-expiry.sh|	<isv:ownCloud@build.opensuse.org> expires: 2022-04-02
|ubuntu:18.10|02-find-key-expiry.sh|	<isv:ownCloud@build.opensuse.org> expires: 2022-04-02
|ubuntu:19.04|02-find-key-expiry.sh|	<isv:ownCloud@build.opensuse.org> expires: 2022-04-02
|ubuntu:19.10|02-find-key-expiry.sh|	<isv:ownCloud@build.opensuse.org> expires: 2022-04-02
|debian:8|02-find-key-expiry.sh|	<isv:ownCloud@build.opensuse.org> expires: 2025-05-20
|debian:9|02-find-key-expiry.sh|	<isv:ownCloud@build.opensuse.org> expires: 2022-04-02
|debian:10|02-find-key-expiry.sh|	<isv:ownCloud@build.opensuse.org> expires: 2022-04-02
|fedora:27|02-find-key-expiry.sh|	<isv:ownCloud@build.opensuse.org> expires: 2021-04-18
|fedora:28|02-find-key-expiry.sh|	<isv:ownCloud@build.opensuse.org> expires: 2021-04-18
|fedora:29|02-find-key-expiry.sh|	<isv:ownCloud@build.opensuse.org> expires: 2021-04-18
|fedora:30|02-find-key-expiry.sh|	<isv:ownCloud@build.opensuse.org> expires: 2021-04-18
|fedora:31|02-find-key-expiry.sh|	<isv:ownCloud@build.opensuse.org> expires: 2021-04-18
|centos:6|02-find-key-expiry.sh|	<isv:ownCloud@build.opensuse.org> expires: 2021-04-18
|centos:7|02-find-key-expiry.sh|	<isv:ownCloud@build.opensuse.org> expires: 2021-04-18
|centos:8|02-find-key-expiry.sh|	<isv:ownCloud@build.opensuse.org> expires: 2021-04-18
|opensuse/leap:42.3|02-find-key-expiry.sh|	<isv:ownCloud@build.opensuse.org> expires: 2021-04-18
|opensuse/leap:15.1|02-find-key-expiry.sh|	<isv:ownCloud@build.opensuse.org> expires: 2021-04-18
|opensuse/leap:15.2|02-find-key-expiry.sh|	<isv:ownCloud@build.opensuse.org> expires: 2021-04-18
|ubuntu:18.04|find-cloud-providers-ini.sh|	ls: cannot access '/usr/share/cloud-providers/*.ini': No such file or directory
|ubuntu:18.10|find-cloud-providers-ini.sh|	ls: cannot access '/usr/share/cloud-providers/*.ini': No such file or directory
|ubuntu:19.04|find-cloud-providers-ini.sh|	-rw-r--r-- 1 root root 102 Jan 28 18:21 /usr/share/cloud-providers/com.owncloud.desktopclient.ini
|ubuntu:19.10|find-cloud-providers-ini.sh|	-rw-r--r-- 1 root root 102 Jan 28 18:18 /usr/share/cloud-providers/com.owncloud.desktopclient.ini
|debian:10|find-cloud-providers-ini.sh|	-rw-r--r-- 1 root root 102 Jan 28 18:19 /usr/share/cloud-providers/com.owncloud.desktopclient.ini

**Comment by jnweiger** [comment]
The 2.6.1 packages are on the mirrors, https://github.com/owncloud/client/releases has the links!

**Comment by HanaGemela** [comment]
Apart from the usual `nothing provides nautilus-python needed by owncloud-client- nautilus-2.6.1-2071.1.x86_64` on Centos 8, smoke test has passed 

[Smoke test, 2.6.1.pdf](https://github.com/owncloud/client/files/4133912/Smoke.test.2.6.1.pdf)

**Comment by HanaGemela** [comment]
@dragotin the packages are ready

**Comment by TheOneRing** [comment]
@HanaGemela why is this issue still open?

**Comment by HanaGemela** [comment]
@TheOneRing I wanted to close it when https://github.com/owncloud/client/issues/7633 is closed... but it probably doesn't need to wait
