### ISSUE TITLE
Release 2.7.4

### ISSUE THREAD

**Issue by TheOneRing** [owncloud/client#7966]
### Create Changelog

* [ ] DEV: Update [ChangeLog](https://confluence.owncloud.com/display/OG/ChangeLog)
* [ ] QA: 1h later check [ChangeLog on website](https://owncloud.org/changelog/desktop-client/)

### Prerequisites

* [ ] QA: Update [Test Plans](https://confluence.owncloud.com/display/OG/Test+Plan+Update) 
* [x] QA: Update [documentation](https://confluence.owncloud.com/display/OG/Documentation)
* [x] QA: Check the translations coming from [Transifex](https://confluence.owncloud.com/display/OG/Online+Updater%2C+Crash+reporter%2C+Transifex#OnlineUpdater,Crashreporter,Transifex-Transifex)
* [x] DEV: Check [dependencies](https://confluence.owncloud.com/display/OG/Dependencies) for updates
* [x] DEV: Branch off a release branch called e.g. `release-2.x.y`  (or do the release in a `2.x` version branch? DECISION NEEDED)
* [x] DEV: bump VERSION.cmake in master to say 2.(x+1).0 unless already done.
* [x] +++ DEV: Announce feature freeze
* [x] +++ DEV: Prepare ci to base daily builds on the new branch

### Build Beta4
* [x] DEV: Create tag, ensure MIRALL_VERSION_SUFFIX to be correct
* [x] DEV: Create [builds](https://handbook.owncloud.com/release_processes/client/build.html#sprint-build) for theme 'ownCloud' and 'testpilotcloud'

### Build Beta5
* [x] +++ DEV: Create tag, ensure MIRALL_VERSION_SUFFIX to be correct
* [x] QA: Create [builds](https://confluence.owncloud.com/display/OG/Build+and+Tags#BuildandTags-Sprintbuild) for theme 'ownCloud' and 'testpilotcloud'
* [x] QA: Check the new subfolder of [testing download](https://download.owncloud.com/desktop/ownCloud/testing/) if `*tar.xz.asc` files are there. If not follow the [instructions](https://github.com/owncloud/enterprise/wiki/Desktop-Signing-Knowledge) #8109 
* [x] +++ Draft a GitHub release, provide changelog (via calens) and links to all builds
* [x] QA: Add a link to Beta5 to https://owncloud.com/beta-testing/#desktop-beta @Marketing
* [x] QA: Inform [stakeholders](https://confluence.owncloud.com/display/OG/Marketing+and+Communication#MarketingandCommunication-InformStakeholdersAfterSuccessfulSprintBuild)
  - https://owncloud.com/news/upcoming-desktop-client-2-7-testing/
  - https://twitter.com/ownCloud/status/1311276067060158466
* [ ] +++ QA: Inform subscribers of the beta program about a new version for testing @Marketing
* [ ] +++ Add the new version to the [online updater](https://confluence.owncloud.com/display/OG/Online+Updater%2C+Crash+reporter%2C+Transifex#OnlineUpdater,Crashreporter,Transifex-ConfigUpdate) in beta channel

### Build RC1
* [X] +++ DEV: Create tag, ensure MIRALL_VERSION_SUFFIX to be correct
* [X] QA: Create [builds](https://confluence.owncloud.com/display/OG/Build+and+Tags#BuildandTags-Sprintbuild) for theme 'ownCloud' and 'testpilotcloud'
* [X] +++ QA: Check the new subfolder of [testing download](https://download.owncloud.com/desktop/ownCloud/testing/) if `*tar.xz.asc` files are there. **Missing** -> https://github.com/owncloud/client/issues/8109
* [x] +++ Draft a GitHub release, provide changelog (via calens) and links to all builds
* [x] +++ Linux docker install tests
* [x] +++ Changelog testing https://github.com/owncloud/client/releases/tag/v2.7.0-rc1
* [x] QA: Add a link to RC1 to https://owncloud.com/beta-testing/#desktop-beta @Marketing
* [x] QA: Inform [stakeholders](https://confluence.owncloud.com/display/OG/Marketing+and+Communication#MarketingandCommunication-InformStakeholdersAfterSuccessfulSprintBuild)
* [ ] +++ QA: Inform subscribers of the beta program about a new version for testing @Marketing
* [ ] +++ Testpilot only: Add the new version to the [online updater](https://confluence.owncloud.com/display/OG/Online+Updater%2C+Crash+reporter%2C+Transifex#OnlineUpdater,Crashreporter,Transifex-ConfigUpdate) in beta channel

### QA

+++ Must have RC1 before entering here

#### DEV QA
* [ ] DEV: [Smoke test](https://confluence.owncloud.com/display/OG/Manual+Tests#ManualTests-DEVSmokeTest)
* [x] DEV: Run [automated tests](https://confluence.owncloud.com/display/OG/Automated+Tests)
#### BTR QA
* [ ] QA: Inform subscribers of the beta program about a new version for testing
* [x] QA: [Antivirus scan](https://confluence.owncloud.com/display/OG/Virus+Scanning)
* [ ] QA: Changelog testing [Add link to 'Test Results 2.x.x' issue here]
* [ ] QA: [Regression test](https://confluence.owncloud.com/display/OG/Manual+Tests#ManualTests-RegressionTest)

### After QA Approval

* [x] DEV: Remove git suffix in `MIRALL_VERSION_SUFFIX` in [`VERSION.cmake`](https://confluence.owncloud.com/display/OG/Branching+Off#BranchingOff-VERSION.cmake)
* [x] DEV: Prepare the changelog on the release branch
* [x] DEV: On release(?) branch create a **signed** [tag](https://confluence.owncloud.com/display/OG/Build+and+Tags#BuildandTags-clientrepository) v2.x.z
* [x] DEV: Create the same tag on branch 2.6 of [_client-plugin-vfs-win_](https://confluence.owncloud.com/display/OG/Build+and+Tags#BuildandTags-client-plugin-vfs-win)
* [x] DEV: Create the same tag on branch 2.6 of [_wip-msi_](https://confluence.owncloud.com/display/OG/Build+and+Tags#BuildandTags-wip-msi)
* [x] DEV: Create same tag for [Windows toolchain](https://confluence.owncloud.com/display/OG/Build+and+Tags#BuildandTags-Windowstoolchain)
* [ ] Notify marketing to remove beta section from the webpage 

### Final Rebuild
* [x] QA: Bump `MIRALL_VERSION_PATCH` in [`VERSION.cmake`](https://confluence.owncloud.com/display/OG/Branching+Off#BranchingOff-PatchRelease)
* [x] QA: Adjust [Linux Templates](https://confluence.owncloud.com/display/OG/Branching+Off#BranchingOff-Linuxtemplates) to support the next patch release version (e.g. 2.6.2)
* [x] QA: Trigger the [build job](https://confluence.owncloud.com/display/OG/Build+and+Tags#BuildandTags-Finalbuild) 
* [ ] QA: Ping marketing to do their [actions](https://confluence.owncloud.com/display/OG/Marketing+and+Communication#MarketingandCommunication-Marketingtasks)
* [ ] QA: Create [a (draft) release](https://github.com/owncloud/client/releases) with Download links - save as a draft until smoke tested
* [ ] QA: Create a new release issue for a branded release if needed (2.7.0: include https://github.com/owncloud/ownbrander/issues/942)
* [ ] QA: Give [heads-up](https://confluence.owncloud.com/display/OG/Marketing+and+Communication#MarketingandCommunication-Heads-upbeforethefinalrelease) before the final release 

### Final QA

* [x] QA: [Smoke test](https://confluence.owncloud.com/display/OG/Manual+Tests#ManualTests-SmokeTest)
* [x] QA: Check if [GitHub download links](https://github.com/owncloud/client/releases) point to correct location
* [x] QA: Publish the release in GitHub
* [x] QA: Check [minimum.supported.desktop.version](https://github.com/owncloud/core/blob/master/config/config.sample.php#L1367) on the server

### Communicate the Availability

* [ ] QA: Announce on [central](https://confluence.owncloud.com/display/OG/Marketing+and+Communication#MarketingandCommunication-Central) listed in [Category News, desktop tag](https://central.owncloud.org/tags/c/news/desktop)
* [ ] QA: Inform [stakeholders](https://confluence.owncloud.com/display/OG/Marketing+and+Communication#MarketingandCommunication-InformStakeholdersaboutFinal)
* [ ] QA: Inform [packagers](https://confluence.owncloud.com/display/OG/Marketing+and+Communication#MarketingandCommunication-Packagers) - ping @dragotin (openSUSE)

### Final Infrastructure Check

* [ ] QA/DEV: Update [stable channel](https://confluence.owncloud.com/display/OG/Online+Updater%2C+Crash+reporter%2C+Transifex#OnlineUpdater,Crashreporter,Transifex-UpdatetheUpdater) in the owncloud hosted auto updater
* [ ] QA/DEV: Ensure that the [client patch release template](https://github.com/owncloud/client/blob/master/.github/patch_release_template.md) is up to date and in sync with other client templates
* [ ] +++ template update back log: https://github.com/owncloud/handbook/pull/271
* [ ] QA: Update [supported platforms](https://confluence.owncloud.com/display/OG/Supported+Platforms)

### A Few Days After the Release

* [ ] DEV: Check the [crash reporter](https://confluence.owncloud.com/display/OG/Online+Updater%2C+Crash+reporter%2C+Transifex#OnlineUpdater,Crashreporter,Transifex-CrashReporter) for bad/frequent crashes
* [ ] +++ (2.7 release only) Check https://github.com/owncloud/ownbrander/issues/942

# Issues found during QA
* https://github.com/owncloud/client/issues/8109 [QA] beta5, rc1: *.tar.xz.asc *.pkg.sig files are missing

**Comment by TheOneRing** [comment]
https://download.owncloud.com/desktop/ownCloud/testing/2.7.0.1871-v270beta1/
https://download.owncloud.com/desktop/testpilotcloud/testing/2.7.0.1872-v270beta1/

**Comment by jnweiger** [comment]
https://download.owncloud.com/desktop/ownCloud/testing/2.7.0.1947-v270beta2/

**Comment by TheOneRing** [comment]
https://download.owncloud.com/desktop/testpilotcloud/testing/2.7.0.1952-v270beta2/

**Comment by jnweiger** [comment]
|Environment||
|-|-|
|date| Thu Aug 13 16:17:01 CEST 2020
|repourl| https://download.owncloud.com/desktop/testpilotcloud/testing/2.7.0.1952-v270beta2/linux/
|package| testpilotcloud-client

|Platform|Test|Result|
|-|-|-|
|centos:7|01_cmd_vers.sh|       testpilotcloud version 2.7.0v270beta2 (build 1952)
|centos:8|01_cmd_vers.sh|       testpilotcloud version 2.7.0v270beta2 (build 1952)
|debian:9|01_cmd_vers.sh|       testpilotcloud version 2.7.0v270beta2 (build 1952)
|debian:10|01_cmd_vers.sh|      testpilotcloud version 2.7.0v270beta2 (build 1952)
|fedora:31|01_cmd_vers.sh|      testpilotcloud version 2.7.0v270beta2 (build 1952)
|fedora:32|01_cmd_vers.sh|      testpilotcloud version 2.7.0v270beta2 (build 1952)
|Linux_Mint_19|01_cmd_vers.sh|  dpkg-query: package 'testpilotcloud-client' is not installed
|ubuntu:18.04|01_cmd_vers.sh|   testpilotcloud version 2.7.0v270beta2 (build 1952)
|ubuntu:19.10|01_cmd_vers.sh|   testpilotcloud version 2.7.0v270beta2 (build 1952)
|ubuntu:20.04|01_cmd_vers.sh|   testpilotcloud version 2.7.0v270beta2 (build 1952)
|opensuse/leap:15.1|01_cmd_vers.sh|     testpilotcloud version 2.7.0v270beta2 (build 1952)
|opensuse/leap:15.2|01_cmd_vers.sh|     testpilotcloud version 2.7.0v270beta2 (build 1952)

**Comment by jnweiger** [comment]
* [ ] to be tested with RC1: https://github.com/owncloud/ownbrander/issues/942

**Comment by TheOneRing** [comment]
For the release announcement we need to mention the deprecation of servers < 10.
- [ ] Announce removal compatibility with servers < 10

**Comment by jnweiger** [comment]
Client Linux docker install test results:

|Environment||
|-|-|
|date| Thu Sep 24 19:45:20 CEST 2020
|repourl| https://download.owncloud.com/desktop/ownCloud/testing/2.7.0.2141-v270beta5/linux
|package| owncloud-client

|Platform|Test|Result|
|-|-|-|
|centos:7|01_cmd_vers.sh|       ownCloud version 2.7.0v270beta5 (build 2141)
|centos:8|01_cmd_vers.sh|       ownCloud version 2.7.0v270beta5 (build 2141)
|debian:9|01_cmd_vers.sh|       ownCloud version 2.7.0v270beta5 (build 2141)
|debian:10|01_cmd_vers.sh|      ownCloud version 2.7.0v270beta5 (build 2141)
|fedora:31|01_cmd_vers.sh|      ownCloud version 2.7.0v270beta5 (build 2141)
|fedora:32|01_cmd_vers.sh|      ownCloud version 2.7.0v270beta5 (build 2141)
|Linux_Mint_19|01_cmd_vers.sh|  dpkg-query: package 'owncloud-client' is not installed
|Linux_Mint_19|01_cmd_vers.sh|  Use dpkg --info (= dpkg-deb --info) to examine archive files,
|Linux_Mint_19|01_cmd_vers.sh|  and dpkg --contents (= dpkg-deb --contents) to list their contents.
|ubuntu:18.04|01_cmd_vers.sh|   ownCloud version 2.7.0v270beta5 (build 2141)
|ubuntu:19.10|01_cmd_vers.sh|   ownCloud version 2.7.0v270beta5 (build 2141)
|ubuntu:20.04|01_cmd_vers.sh|   ownCloud version 2.7.0v270beta5 (build 2141)
|opensuse/leap:15.1|01_cmd_vers.sh|     ownCloud version 2.7.0v270beta5 (build 2141)
|opensuse/leap:15.2|01_cmd_vers.sh|     ownCloud version 2.7.0v270beta5 (build 2141)

**Comment by jnweiger** [comment]
Generated github release text snippet with `release/desktop/prep_release_text.sh v2.7.0-beta5`

**Comment by jnweiger** [comment]
Client Linux docker install test results:
|Environment||
|-|-|
|date| Mon Oct 12 21:52:27 CEST 2020
|repourl| https://download.owncloud.com/desktop/ownCloud/testing/2.7.0-v270rc1.2254/linux
|package| owncloud-client

|Platform|Test|Result|
|-|-|-|
|centos:7|01_cmd_vers.sh|       ownCloud 2.7.0v270rc1 (build 2254) Oct  9 2020 13:12:14
|centos:8|01_cmd_vers.sh|       ownCloud 2.7.0v270rc1 (build 2254) Oct  9 2020 12:56:43
|debian:9|01_cmd_vers.sh|       ownCloud 2.7.0v270rc1 (build 2254) Oct  9 2020 12:56:43
|debian:10|01_cmd_vers.sh|      ownCloud 2.7.0v270rc1 (build 2254) Oct  9 2020 12:56:43
|fedora:31|01_cmd_vers.sh|      ownCloud 2.7.0v270rc1 (build 2254) Oct  9 2020 12:56:43
|fedora:32|01_cmd_vers.sh|      ownCloud 2.7.0v270rc1 (build 2254) Oct  9 2020 12:56:43
|Linux_Mint_19|01_cmd_vers.sh|  dpkg-query: package 'owncloud-client' is not installed
|ubuntu:18.04|01_cmd_vers.sh|   ownCloud 2.7.0v270rc1 (build 2254) Oct  9 2020 12:56:43
|ubuntu:19.10|01_cmd_vers.sh|   ownCloud 2.7.0v270rc1 (build 2254) Oct  9 2020 12:56:43
|ubuntu:20.04|01_cmd_vers.sh|   ownCloud 2.7.0v270rc1 (build 2254) Oct  9 2020 12:56:43
|opensuse/leap:15.1|01_cmd_vers.sh|     ownCloud 2.7.0v270rc1 (build 2254) Oct  9 2020 12:56:43
|opensuse/leap:15.2|01_cmd_vers.sh|     ownCloud 2.7.0v270rc1 (build 2254) Oct  9 2020 12:56:43

**Comment by jnweiger** [comment]
Untestable changelog items:
* Bugfix - Fix support of adler32 checksums with Windows virtual files support: #7999

**Comment by TheOneRing** [comment]
> Untestable changelog items:
> 
>     * Can neither reprodue nor confirm a fix
>       
>       * Bugfix - Fix support of adler32 checksums with Windows virtual files support: #7999
Can be confirmed by reporting customer
>       * Change - The settings ui shows a prompt for a few seconds: #7925
Explained in ticket
> 
>     * Cannot reproduce but code change looks sane
>       
>       * Bugfix - Use the correct style for the folder wizard: #8027
The folder wizard did not look like the other wizards on mac (poor harry 🤣 ) now he does
>       * Change - Don't hardcode a plugin location: #3839
>       * Change - Use the checksum type specified by the server by default: #7989
You will no longer get multiple "computing checksum" messages per file
> 
> 
> Failed tests
> 
>     * Bugfix - Use the same HDPI for the crash reporter as for the client: #8042 -- window should be resizeable. It is not.

Was not readable or usable due to hdpi issues those are fixed, no need for resizing.

**Comment by jnweiger** [comment]
Reopened #7862 -- we could not find a way to prevent chunking from the server side.

**Comment by jnweiger** [comment]
@michaelstingl @TheOneRing status 'In Dev'
 please ping, when ready for next RC

**Comment by jnweiger** [comment]
RC3 is ready for testing:
* https://download.owncloud.com/desktop/ownCloud/testing/2.7.0-rc3.2413/
* https://download.owncloud.com/desktop/testpilotcloud/testing/2.7.0-rc3.2412/

**Comment by jnweiger** [comment]
Reported while testing RC3:

* #8212 [QA] German translation issues

**Comment by jnweiger** [comment]
TODO:
* [ ] decide renaming. Drop the `-client` suffix from packages?

**Comment by dschmidt** [comment]
To be clear: we dropped the `-client` suffix from tarballs and macOS/Windows installers.
Also we streamlined the basenames of all released files. They are now based on `SHORTNAME` (e.g. source tarball used to be based on `OEM_THEME` directly).

For Linux packages nothing changed.

**Comment by jnweiger** [comment]
* [ ] fresh install in Win10
* [ ] fresh install on MacOS
* [x] fresh install on Ubuntu-20.04, 20.10, Fedora32
* [x] Update path tested (ubuntu 20.04): 2.7.0-1 -> 2.7.1+oc-2527 -> 2.7.1+oc25.29
* [ ] upload download exercises
* [ ] version information visible
* [ ] no obvious UI glitches.

**Comment by jnweiger** [comment]
Caveats to be communicated:

* [ ] Fedora users: Fedora-33 is still missing.
* [ ] All Linux users: You must perform manual steps to get 2.7 or any later version. See https://owncloud.com/desktop-app/ -- the old repo cannot receive the updates any more.

**Comment by jnweiger** [comment]
Daily build with Fedora-33 was successful.

**Comment by jnweiger** [comment]
### New issues found during testing client 2.7.4 

(could find a separate release ticket for that one, just pasting results here.)

Test on Win10 Pro 20H2
https://download.owncloud.com/desktop/ownCloud/testing/2.7.4-rc1.2909/win/ownCloud-2.7.4-rc1.2909.x64.msi
https://download.owncloud.com/desktop/testpilotcloud/testing/2.7.4-rc1.2910/linux/download/


* https://github.com/owncloud/client/issues/8312 [QA] win10 VFS gives bad UX, when client is signed out
* https://github.com/owncloud/client/issues/8316 [QA] Win10: office does not report changed dcument when updated from the server
* https://github.com/owncloud/client/issues/8317 [QA] VFS on Win10 is not "recommended" setting in connection wizard
* https://github.com/owncloud/client/issues/8318 [QA] VFS on windows fails with deep tree 
* https://github.com/owncloud/client/issues/8319 [QA] win10 VFS: Sync silently pendig when disk full

potential release blockers:
* #8317 (just a string change)

**Comment by jnweiger** [comment]
## Smoke test final builds:

### Test on Win10 Pro 20H2
https://download.owncloud.com/desktop/ownCloud/stable/2.7.4.2934/win/ownCloud-2.7.4.2934.x64.msi
https://download.owncloud.com/desktop/testpilotcloud/stable/2.7.4.2935/win/testpilotcloud-2.7.4.2935.x86.msi

### Ubuntu_20.04
owncloud-client-2.7.4+oc-2934 from https://download.owncloud.com/desktop/ownCloud/stable/2.7/linux/download/

### Mac
https://download.owncloud.com/desktop/ownCloud/stable/2.7.4.2934/mac/ownCloud-2.7.4.2934.pkg

QA passed :green_heart:

**Comment by TheOneRing** [comment]
Was released
