### ISSUE TITLE
Release 2.7.5

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#8349]
## Reason

* Needed for branded 2.7.5 release - https://github.com/owncloud/enterprise/issues/4297

### Prerequisites

* [ ] QA: Update [Test Plans](https://confluence.owncloud.com/display/OG/Test+Plan+Update) 
* [ ] QA: Update [documentation](https://confluence.owncloud.com/display/OG/Documentation)
* [ ] QA: Check the translations coming from [Transifex](https://confluence.owncloud.com/display/OG/Online+Updater%2C+Crash+reporter%2C+Transifex#OnlineUpdater,Crashreporter,Transifex-Transifex)
* [x] DEV: Check [dependencies](https://confluence.owncloud.com/display/OG/Dependencies) for updates
* [x] DEV: Branch off a release branch called e.g. `release-2.x.y`  (or do the release in a `2.x` version branch? DECISION NEEDED)
* [ ] DEV: bump VERSION.cmake in master to say 2.(x+1).0 unless already done.
* [x] Create testplan ~ticket~ See below.  https://github.com/owncloud/client/issues/8349#issuecomment-758695773

### Build

* [x] QA: Create [builds](https://confluence.owncloud.com/display/OG/Build+and+Tags#BuildandTags-Sprintbuild) for theme 'ownCloud' and 'testpilotcloud'
* [x] QA: Check the new subfolder of [testing download](https://download.owncloud.com/desktop/ownCloud/testing/) if `*tar.xz.asc` files are there. If not follow the [instructions](https://github.com/owncloud/enterprise/wiki/Desktop-Signing-Knowledge)
* [ ] QA: Add a link to RC1 to https://owncloud.com/beta-testing/#desktop-beta @Marketing
* [ ] QA: Inform [stakeholders](https://confluence.owncloud.com/display/OG/Marketing+and+Communication#MarketingandCommunication-InformStakeholdersAfterSuccessfulSprintBuild)

#### DEV QA
* [ ] DEV: [Smoke test](https://confluence.owncloud.com/display/OG/Manual+Tests#ManualTests-DEVSmokeTest)
* [x] DEV: Run [automated tests](https://confluence.owncloud.com/display/OG/Automated+Tests)
#### BTR QA
* [ ] QA: Inform subscribers of the beta program about a new version for testing
* [x] QA: [Antivirus scan](https://confluence.owncloud.com/display/OG/Virus+Scanning)
* [x] QA: Changelog testing --> https://github.com/owncloud/client/issues/8349#issuecomment-758725078
* [x] QA: [Regression test](https://confluence.owncloud.com/display/OG/Manual+Tests#ManualTests-RegressionTest) --> https://github.com/owncloud/client/issues/8349#issuecomment-758695773

### After QA Approval

* [ ] DEV: Remove git suffix in `MIRALL_VERSION_SUFFIX` in [`VERSION.cmake`](https://confluence.owncloud.com/display/OG/Branching+Off#BranchingOff-VERSION.cmake)
* [ ] DEV: On release(?) branch create a **signed** [tag](https://confluence.owncloud.com/display/OG/Build+and+Tags#BuildandTags-clientrepository) v2.x.z
* [ ] DEV: Create the same tag on branch 2.6 of [_client-plugin-vfs-win_](https://confluence.owncloud.com/display/OG/Build+and+Tags#BuildandTags-client-plugin-vfs-win)
* [ ] DEV: Create the same tag on branch 2.6 of [_wip-msi_](https://confluence.owncloud.com/display/OG/Build+and+Tags#BuildandTags-wip-msi)
* [ ] DEV: Create same tag for [Windows toolchain](https://confluence.owncloud.com/display/OG/Build+and+Tags#BuildandTags-Windowstoolchain)
* [ ] DEV: Create same tag (actually a symlink) for [macOS toolchain](https://confluence.owncloud.com/display/OG/Build+and+Tags#BuildandTags-macOStoolchain)

### Final Rebuild

* [ ] QA: Change the date in `ChangeLog` to the date of creating the tag 
* [ ] QA: Bump `MIRALL_VERSION_PATCH` in [`VERSION.cmake`](https://confluence.owncloud.com/display/OG/Branching+Off#BranchingOff-PatchRelease)
* [ ] QA: Adjust [Linux Templates](https://confluence.owncloud.com/display/OG/Branching+Off#BranchingOff-Linuxtemplates) to support the next patch release version (e.g. 2.6.2)
* [ ] QA: Trigger the [build job](https://confluence.owncloud.com/display/OG/Build+and+Tags#BuildandTags-Finalbuild) 
* [ ] QA: Ping marketing to do their [actions](https://confluence.owncloud.com/display/OG/Marketing+and+Communication#MarketingandCommunication-Marketingtasks)
* [ ] QA: Create [a (draft) release](https://github.com/owncloud/client/releases) with Download links - save as a draft until smoke tested
* [ ] QA: Create a new release issue for a branded release if needed
* [ ] QA: Give [heads-up](https://confluence.owncloud.com/display/OG/Marketing+and+Communication#MarketingandCommunication-Heads-upbeforethefinalrelease) before the final release 

### Final QA

* [ ] QA: [Smoke test](https://confluence.owncloud.com/display/OG/Manual+Tests#ManualTests-SmokeTest)
* [ ] QA: Check if [GitHub download links](https://github.com/owncloud/client/releases) point to correct location
* [ ] QA: Publish the release in GitHub
* [ ] QA: Check [minimum.supported.desktop.version](https://github.com/owncloud/core/blob/master/config/config.sample.php#L1367) on the server

### Communicate the Availability

* [ ] QA: Announce on [central](https://confluence.owncloud.com/display/OG/Marketing+and+Communication#MarketingandCommunication-Central) listed in [Category News, desktop tag](https://central.owncloud.org/tags/c/news/desktop)
* [ ] QA: Inform [stakeholders](https://confluence.owncloud.com/display/OG/Marketing+and+Communication#MarketingandCommunication-InformStakeholdersaboutFinal)
* [ ] QA: Inform [packagers](https://confluence.owncloud.com/display/OG/Marketing+and+Communication#MarketingandCommunication-Packagers) - ping @dragotin (openSUSE)

### Final Infrastructure Check

* [ ] QA/DEV: Update [stable channel](https://confluence.owncloud.com/display/OG/Online+Updater%2C+Crash+reporter%2C+Transifex#OnlineUpdater,Crashreporter,Transifex-UpdatetheUpdater) in the owncloud hosted auto updater
* [ ] QA/DEV: Ensure that the [client patch release template](https://github.com/owncloud/client/blob/master/.github/patch_release_template.md) is up to date and in sync with other client templates
* [ ] QA: Update [supported platforms](https://confluence.owncloud.com/display/OG/Supported+Platforms)

### A Few Days After the Release

* [ ] DEV: Check the [crash reporter](https://confluence.owncloud.com/display/OG/Online+Updater%2C+Crash+reporter%2C+Transifex#OnlineUpdater,Crashreporter,Transifex-CrashReporter) for bad/frequent crashes

**Comment by jnweiger** [comment]
Needed for unbranded  2.7.5-RC1 (Linux): https://build.opensuse.org/project/monitor/isv:ownCloud:Qt51210

TODO:
* [X] hook the new Qt 5.12.10 dependencies into client 2.7.5 linux builds
* [X] try trigger https://jenkins.int.owncloud.com/view/client/job/client-trigger-drone/build?delay=0sec daily 2.7: it fails, but it produces a source tar for the next step.
* [x] `build.sh remote-images -param DRONE_TARBALL_URL=https://download.owncloud.com/desktop/testpilotcloud/daily/2.7/source/testpilotcloud-2.7.5-daily20210107.3008.tar.xz`
     ->  https://drone.owncloud.services/client/build-linux/2264/1/7
* [ ] Test drive https://download.owncloud.com/desktop/testpilotcloud/daily/2.7/linux/Ubuntu_20.04  testpilotcloud-client 2.7.5~daily20210108+oc-3012 
      -> https://github.com/owncloud/client/issues/8328#issuecomment-756656880
* [ ] bundle ocqt51210-qtwayland5 with Debian, Fedora and Ubuntu builds. (CentOS and SUSE later, when available)
* [ ] optional: In case we ever need obs.int fallback: `obs-deepcopy-prj.sh -Aint openSUSE.org:isv:ownCloud:Qt51210 desktop:Qt51210`

**Comment by jnweiger** [comment]
|Environment||
|-|-|
|date| Sat Jan  9 04:34:17 CET 2021
|repourl| https://download.owncloud.com/desktop/testpilotcloud/daily/2.7/linux
|package| testpilotcloud-client

|Platform|Test|Result|
|-|-|-|
|centos:7|01_cmd_vers.sh|       2.7.5daily20210109 (build 3024) Jan  9 2021 00:17:05
|centos:8|01_cmd_vers.sh|       2.7.5daily20210109 (build 3024) Jan  6 2021 01:33:14
|debian:9|01_cmd_vers.sh|       2.7.5daily20210109 (build 3024) Jan  6 2021 01:33:14
|debian:10|01_cmd_vers.sh|      2.7.5daily20210109 (build 3024) Jan  6 2021 01:33:14
|fedora:31|01_cmd_vers.sh|      2.7.5daily20210109 (build 3024) Jan  6 2021 01:33:14
|fedora:32|01_cmd_vers.sh|      2.7.5daily20210109 (build 3024) Jan  6 2021 01:33:14
|fedora:33|01_cmd_vers.sh|      2.7.5daily20210109 (build 3024) Jan  6 2021 01:33:14
|ubuntu:18.04|01_cmd_vers.sh|   2.7.5daily20210109 (build 3024) Jan  6 2021 01:33:14
|ubuntu:20.04|01_cmd_vers.sh|   2.7.5daily20210109 (build 3024) Jan  6 2021 01:33:14
|ubuntu:20.10|01_cmd_vers.sh|   2.7.5daily20210109 (build 3024) Jan  6 2021 01:33:14
|opensuse/leap:15.1|01_cmd_vers.sh|     2.7.5daily20210109 (build 3024) Jan  6 2021 01:33:14
|opensuse/leap:15.2|01_cmd_vers.sh|     2.7.5daily20210109 (build 3024) Jan  6 2021 01:33:14
centos:7|15_wayland.sh|        Available: linuxfb, minimal, offscreen, vnc, wayland, xcb.
|centos:8|15_wayland.sh|        Available: linuxfb, minimal, offscreen, vnc, wayland, xcb.
|debian:9|15_wayland.sh|        Available: linuxfb, minimal, offscreen, vnc, wayland, xcb.
|debian:10|15_wayland.sh|       Available: linuxfb, minimal, offscreen, vnc, wayland, xcb.
|fedora:31|15_wayland.sh|       Available: linuxfb, minimal, offscreen, vnc, wayland, xcb.
|fedora:32|15_wayland.sh|       Available: linuxfb, minimal, offscreen, vnc, wayland, xcb.
|fedora:33|15_wayland.sh|       Available: linuxfb, minimal, offscreen, vnc, wayland, xcb.
|ubuntu:18.04|15_wayland.sh|    Available: linuxfb, minimal, offscreen, vnc, wayland, xcb.
|ubuntu:20.04|15_wayland.sh|    Available: linuxfb, minimal, offscreen, vnc, wayland, xcb.
|ubuntu:20.10|15_wayland.sh|    Available: linuxfb, minimal, offscreen, vnc, wayland, xcb.
|opensuse/leap:15.1|15_wayland.sh|      Available: linuxfb, minimal, offscreen, vnc, wayland, xcb.
|opensuse/leap:15.2|15_wayland.sh|      Available: linuxfb, minimal, offscreen, vnc, wayland, xcb.
|centos:7|30_openssl_vers.sh|   Libraries Qt 5.12.10, OpenSSL 1.0.2k-fips  26 Jan 2017
|centos:8|30_openssl_vers.sh|   Libraries Qt 5.12.10, OpenSSL 1.1.1g FIPS  21 Apr 2020
|debian:9|30_openssl_vers.sh|   Libraries Qt 5.12.10, OpenSSL 1.1.0l  10 Sep 2019
|debian:10|30_openssl_vers.sh|  Libraries Qt 5.12.10, OpenSSL 1.1.1d  10 Sep 2019
|fedora:31|30_openssl_vers.sh|  Libraries Qt 5.12.10, OpenSSL 1.1.1g FIPS  21 Apr 2020
|fedora:32|30_openssl_vers.sh|  Libraries Qt 5.12.10, OpenSSL 1.1.1g FIPS  21 Apr 2020
|fedora:33|30_openssl_vers.sh|  Libraries Qt 5.12.10, OpenSSL 1.1.1g FIPS  21 Apr 2020
|ubuntu:18.04|30_openssl_vers.sh|       Libraries Qt 5.12.10, OpenSSL 1.1.1  11 Sep 2018
|ubuntu:20.04|30_openssl_vers.sh|       Libraries Qt 5.12.10, OpenSSL 1.1.1f  31 Mar 2020
|ubuntu:20.10|30_openssl_vers.sh|       Libraries Qt 5.12.10, OpenSSL 1.1.1f  31 Mar 2020
|opensuse/leap:15.1|30_openssl_vers.sh| Libraries Qt 5.12.10, OpenSSL 1.1.0i-fips  14 Aug 2018
|opensuse/leap:15.2|30_openssl_vers.sh| Libraries Qt 5.12.10, OpenSSL 1.1.1d  10 Sep 2019

**Comment by TheOneRing** [comment]
https://download.owncloud.com/desktop/ownCloud/testing/2.7.5-rc1.3035/
https://download.owncloud.com/desktop/testpilotcloud/testing/2.7.5-rc1.3037/

**Comment by iHerrmann77** [comment]
> https://download.owncloud.com/desktop/ownCloud/testing/2.7.5-rc1.3035/
something in Sentry to check before issue 3347abab-ae3e-4eaa-9ab3-2cf0710dcf38

> https://download.owncloud.com/desktop/testpilotcloud/testing/2.7.5-rc1.3037/

**Comment by TheOneRing** [comment]
You remove the sync root manually?

**Comment by iHerrmann77** [comment]
> You removed the sync root manually?

No, just installed the client

**Comment by jnweiger** [comment]
issues opened while testing:

* [ ] CHANGELOG.md in 2.7.5-RC1 is not up to date https://github.com/owncloud/client/issues/8351

**Comment by jnweiger** [comment]
## Changelog Testplan

* [ ] Fix potential crashes with the remove all dialog: #8314 
* [ ] Remove stray placeholders: #8326 
* [ ] Re-synchronizing (some) virtual files again, and again #8326 
* [ ] Fix placeholder detection for cfapi #8343 + https://gitea.owncloud.services/client/client-plugin-vfs-win/pulls/19

**Comment by jnweiger** [comment]
### New issues opened while testing:

* [ ] CHANGELOG.md in 2.7.5-RC1 is not up to date https://github.com/owncloud/client/issues/8351

### Issues reproduced while testing

* [ ] Crash on missing sync root  #8321

**Comment by jnweiger** [comment]
@michaelstingl @TheOneRing please decide about RC2 and prepare one if so. This ticket is back to RC needed for now.

**Comment by jnweiger** [comment]
https://github.com/owncloud/client/releases/tag/v2.7.5-rc2 is available for testing!

**Comment by TheOneRing** [comment]
https://github.com/owncloud/client/releases/tag/v2.7.5-rc4

**Comment by jnweiger** [comment]
Tested with RC4 the relevant tests and basic smoke testing on all supported platfoms. The major bulk of tests was erformed only with RC2, as agreed.

@TheOneRing QA passed with minor issues. :shipit:

**Comment by jnweiger** [comment]
|Environment||
|-|-|
|date| Fri Jan 29 17:03:17 CET 2021
|repourl| https://download.owncloud.com/desktop/ownCloud/stable/2.7.5.3180/linux
|package| owncloud-client

<details><summary>Test details (click to view)</summary>

|Platform|Test|Result|
|-|-|-|
|ubuntu:20.04|01_cmd_vers.sh|	2.7.5 (build 3180) Jan 28 2021 15:10:33
|ubuntu:20.04|10_key_expiry.sh|	<devel@s2.owncloud.com> expires: 2022-01-28
|ubuntu:20.04|15_wayland.sh|	Available: linuxfb, minimal, offscreen, vnc, wayland, xcb.
|ubuntu:20.04|20_qttrans_de.sh|	OK
|ubuntu:20.04|30_openssl_vers.sh|	Libraries Qt 5.12.10, OpenSSL 1.1.1f  31 Mar 2020
|ubuntu:20.04|50_sync_excl.lst.sh|	418 /etc/ownCloud/sync-exclude.lst

</details>
----
