### ISSUE TITLE
Add new squish tests (or extend existing) for desktop-client

### ISSUE THREAD

**Issue by gabi18** [owncloud/client#8888]
## Description
Follow up of #8651 which covers tests from patch release test plan, see https://github.com/owncloud/client/issues/8651#issuecomment-857373491.

This issue is about adding tests (or extend tests) for test cases of the minor release test plan, see [Regression_Test_Plan_Minor_Release](https://github.com/owncloud/QA/blob/master/Desktop/Regression_Test_Plan_Minor_Release.md).
Already existing tests: see  https://github.com/owncloud/client/tree/master/test/gui.

## To-Do:
__1. Settings windows - Login__
- [ ] __5__ Introduce wrong credentials (extend tst_addAccount)
- [ ] ...
 
__2. Folders__
- [ ] __2__ Create folder with long name
- [ ] __3__ Create folder with special chars in name
- [ ] __6__ Sync five subfolders
- [ ] __7__ Sync five subfolders with files
- [ ] __9__ Copy a folder
- [ ] __10__ Create a subfolder with long name
- [ ] ...

...
