### ISSUE TITLE
VFS Testplan Release Desktop 2.10.0

### ISSUE THREAD

**Issue by gabi18** [owncloud/client#9312]
### Template: 
[Test_Plan_VFS.md](https://github.com/owncloud/QA/blob/master/Desktop/Test_Plan_VFS.md)

## Prerequirements

Prepare a server with the latest version on Hetzner ([make_oc10_apps.sh](https://github.com/owncloud/QA/blob/master/tools/hetzner-deploy/make_oc10_apps.sh)) or locally e.g. `docker run -ti --rm -p 8080:8080 owncloud/server:10.8`

-> https://oc1090-web-app-470-20211220.jw-qa.owncloud.works

Have a client build ready, link URL here:

-> https://download.owncloud.com/desktop/ownCloud/testing/2.10.0-rc2.6346/win

Test environment:
- Windows 10 -> add the version here (`winver` or client 'About' 'Versions' tab ) 
- Install LibreOffice and CPUSTRES (activate 4-5 threads to get a CPU load of appr. 60 %)

### VFS Documentation

- https://doc.owncloud.com/desktop/2.9/vfs.html
- https://www.userfilesystem.com/programming/faq/#nav_howdoesthefreeupspacemenuworks
- https://docs.microsoft.com/en-us/windows/win32/cfapi/build-a-cloud-file-sync-engine#cloud-files-api-architecture

### General

- Enable the client logging (on 'Settings' 'Log Settings')
- Login to the server and watch the trash bin

## Testing

* [x] Add an account and connect to the server with VFS ON (@Talank)
  * [x] 'Open folder' (Explorer) and check that all files are virtual, Status: placeholder file (cloud icon)
  * [x] open an existing file -> file is physically available, Status: full file (green unfilled circle with green check mark)
  * [ ] create a new file locally, edit, save and exit -> if locked (ie. LibreOffice not exited) the file icon stays in "cycle mode", see "Tests when a file or folder is locked
  * [x] right click: 'Free up space' -> placeholder is created, 'Activity' 'Sync Protocol' shows "Replaced by virtual file" 
  * [x] create several new files more, edit some -> files are synced if they are not locked
  * [ ] on client dot menu: 'Availibility' 'Free up local space' -> placeholder for all files are created (files are dehydrated) 
            -  ❗ I do not see the Free up local space, there is just free up space when I right click on the file/folder via explorer -> https://github.com/owncloud/client/issues/9314

* [x] Tests concerning free up space (@Talank)
  * [x] Create several new files in a subfolder, edit some of them, also have dehydrated files available
  * [x] 'Open folder', right click on the folder in Explorer, 'Free up space' in Windows file menu -> all files are dehydrated, check all placeholder files are there, check trash bin on server
  * [ ] Create a new folder and move (also use 'Cut' and'Paste') several dehydrated files into it -> all files are moved into the folder, remain dehydrated and disappear from previous location (known issue: https://github.com/owncloud/client/issues/9101)
           -  ❗ The files that are pasted after cut are downloaded. Also, the folder (which is newly created) where I paste all the files shows the status "not synced" even if all the files inside the folder shows status downloaded (unfilled green circle with green tick)
     
- Use file lock detection tool such as https://lockhunter.com/?utm_source=saashub&utm_medium=marketplace&utm_campaign=saashub
- LO means LibreOffice, which locks the files that it opens on Windows

* [ ] Tests when a file or folder is locked (@saw-jan )
  * [x] Open a file in LibreOffice, edit, save, don't exit, which results in having the document file locked
  * [x] 'Free up space' in Explorer on the locked file -> no red error message, client shows "i" (Status: spinning icon), Activity tells that file is in use
  * [x] Exit libreoffice -> file is dehydrated correctly (Status: placeholder) after a few seconds
    - ~❗ (doesn't change to placeholder)~
    - ~❗ file is currently in use message persists~
    - ~❗ (file is not synced automatically) (owncloud/client#9315)~
    - ~force sync works~
  * [x] 'Free up space' in Explorer on the parent directory -> locked file stays locked, other non locked files are dehydrated
  * [x] Create file via LibreOffice, keep it open in LO, file is not synced. As soon as LO is closed, file is synced.
     - ~❗ (file is not synced automatically) (owncloud/client#9315)~
     - ~❗ `file is currently in use` message persists~
     - ~force sync works~
  * [x] Move locally locked file on the server -> Creates a new file, syncs it down
      - ~❗(not synced automatically) (owncloud/client#9315)~
      - ~force sync works~
  * [ ] Delete locked file on the server -> Red error message appears, file stays locally. After LO is closed, file is removed if file was NOT changed locally after the delete.
      - ❗(Cannot see red error message in the client) the status icon changes from `green tick` to `i` in the account window
      - ~❗(file is not synced automatically) (owncloud/client#9315)~
      - ~force sync works~
  * [ ] Delete locked file on the server -> Red error message appears, file stays locally. Now, change the file locally in LO and save. After LO is closed, file is synced to cloud as new file. No version history any more.
     - ❗(Cannot see red error message)
     - ~❗(file is not synced automatically) (owncloud/client#9315)~
     - ~force sync works~
  * [x] Lock file that is in sync locally with LO. Move the file on server side. Save File and close LO -> The file gets synced to the server with the former name and appears as new file.
     - ~❗ (file is not synced automatically) (owncloud/client#9315)~
     - ~force sync works~
  * [x] Create a directory and open a file within that with LO. Rename the parent dir on the server and leave the file unchanged. After LO is closed, the directory is renamed locally.
     - ~❗(not synced automatically) (owncloud/client#9315)~
     - ~force sync works~
  * [x] Create a directory and open a file within that with LO. Rename the parent dir on the server change the file in LO. Save and close after the parent dir rename failed. After close of LO, dir gets renamed and file uploaded.
      - ~❗(not synced automatically) (owncloud/client#9315)~
      - ~force sync works~

* [x] File Operations @gabi18 
  * [x] Move file and directory locally -> both dehydrated and hydrated files are moved locally and accordingly on the server
  * [x] Move an empty dehydrated folder inside the sync root and to a location outside the sync root -> accordingly moved on server and locally
  * [x] Move file and directory on the server -> Both dehydrated and hydrated files are moved accordingly locally
  * [x] Create file in directory and open with LO. Do not change. Remove the directory on the server. After closing LO, directory and file are removed. (See #9293) -> ~❗folder and file aren't removed after closing LO -> #9316~
  * [x] Create file in directory and open with LO. Remove the directory on the server. Edit the file and save it. After closing LO, directory and file are created again. (See #9293)
  * [x] On server: create FolderA and 2 files NewFile and Newfile inside FolderB
    * [x] watch client -> a red warning message "...file name clash..." is shown for a while then 'i' icon, 'Not synced' tab shows file name clash
    * [x] 'Open folder' and check status of FolderB and NewFile -> spinning icon ("cycle mode") for folder and file
    * [ ] Move FolderB to anNew text fileother place (outside the syncroot) -> expected: FolderB is moved to new location and deleted on the server -> NOT ok FolderB is moved locally but not deleted on server -> #9311 
   * [x] Create a new folder in Explorer and press 'Enter' twice, stay inside the folder for more than 30 seconds
     * [x] leave the folder and check status icon -> should change to cloud icon (see #8926) XXX

* [x] Test with a long path (make sure LongPathsEnabled in Windows registry is off ** )
  (@Talank )
  * [ ] Create a file with a long path (> 260)
  * [ ] 'Free up space' -> no red error message
      - ❗I created a file (233 characters filename) inside a folder. The file is not synced and the status in `Not Synced` tab shows that the file has been `Blacklisted`. Also, I see the red error message in the main screen of the client that says the file name is too long.
  -> https://github.com/owncloud/client/issues/9312#issuecomment-1000208288
* [x] Test with ignored or 'problematic' files, see https://doc.owncloud.com/desktop/2.9/filenames.html (@Talank )
  * [ ] Test with files that are on the ignore list, ie. files with the extension `.part`.
          - ❗ Everything looks good when the part file is created in the local sync dir. But if I copy it from outside, then the status becomes `cycle` and I can not even see any new logs.
  * [ ] Create files that contain ':' or have a trailing space, they will be ignored in the sync
          - ❗ the file with : can not be created in windows. It is ignored if syncing from server; However, the file that is ignored has multiple entries in `not synced` tab
  * [ ] Create files with problematic name like `CON`, `PRN` or `AUX`, expect reasonable sync indicator icons
          - ❗ file with reserve names are ignored, while syncing from server. I do not understand what is "reasonable sync indicator" here

* [x] Switch between VFS ON/OFF (@saw-jan)
  * [x] Add a second account with VFS OFF
  * [x] Switch to VFS ON using client dot menu -> file status changes (Status: full file)
  * [x] in Explorer: right-click on a folder and 'Free up space' -> all files in folder get dehydrated (placeholder file, Status: cloud icon)
  * [ ] ~on client dot menu: 'Availibility' 'Free up space' -> all files in sync root get dehydrated~
      - ~❗https://github.com/owncloud/client/issues/9314#issuecomment-1000064986~
      - `Availibility` menu was intended to remove
  * [x] Switch back to VFS OFF -> all files are physically (overlay icons are shown)

* [x] Client sync operations (@saw-jan)
  * [x] 'Pause sync' (on client dot menu) while client is syncing  -> current 2.10 behaviour: 'Not Synced' tab shows entry "Operation canceled" ... "Fatal error" => Known issue: should NOT be a fatal error but a less severe status  
  * [x] 'Resume sync' -> sync is continued and runs successfully

* [x] Connect to a server account having "big" data prepared VFS ON (@saw-jan)
  * [x] many files
  * [x] many subfolders
  * [x] large file
  * [ ] ...

  TODO: Provide a zip-file containing test-data e.g. on https://download.owncloud.com/desktop/ or in the issue (test plan ticket)

* [ ] Switch machine status (standby, suspend, hybernate ...)
  * [ ] Close lid of a laptop while client is syncing -> reopen and see client continues the sync 
  * [ ] On Windows VM command line: call shutdown /h -> client continues after relogin 
  * [ ] ...

** https://docs.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation?tabs=cmd

**Comment by michaelstingl** [comment]
> * expect reasonable sync indicator icons

@dragotin could you clarify "reasonable sync indicator"?

**Comment by Talank** [comment]
[logs.zip](https://github.com/owncloud/client/files/7767791/logs.zip)
@michaelstingl here is the logs, that contains the multiple entries of filename with `:`

**Comment by dragotin** [comment]
I tried to reproduce the long file name (not path...) issue. I created a file name with length of 229 characters plus 4 chars extension (.txt). That is not easy to create (some tools as notepad++ just do not do it) but it is possible to rename a file with shorter name to the long name.

The rename on works fine, and is also done on the server. 

If I change the file on client side so that it needs to be synced to the server, the attempt results in an error like this on the server:
```
"user":"klaas","app":"PHP","method":"PUT","url":"\/owncloud\/remote.php\/dav\/files\/klaas\/ownCloud\/kUDrWWpNGN8EdwfEX01LAgrn_VNbtFDUACUvuejdeIMP0_N9fv1f4YM5kvP3D3AiNQjiAVHQFPaA2jU8nWc5HuJ9xT891N2p2__PiURYvWL1S6HJuv3XEMn2f54t2Z5hGgj9MBqRO4PUZkSkq9wMz5_lI3TaXiaQmYC6QMeWCkSyMtfvqyliog8d7DgCDiHFBwxDqc41iUjEcGmiAt3ZOuxhjSoz68fDExcD.txt","message":"fopen(\/mnt\/data\/files\/klaas\/files\/ownCloud\/kUDrWWpNGN8EdwfEX01LAgrn_VNbtFDUACUvuejdeIMP0_N9fv1f4YM5kvP3D3AiNQjiAVHQFPaA2jU8nWc5HuJ9xT891N2p2__PiURYvWL1S6HJuv3XEMn2f54t2Z5hGgj9MBqRO4PUZkSkq9wMz5_lI3TaXiaQmYC6QMeWCkSyMtfvqyliog8d7DgCDiHFBwxDqc41iUjEcGmiAt3ZOuxhjSoz68fDExcD.txt.ocTransferId16827488.part): failed to open stream: File name too long at \/var\/www\/owncloud\/lib\/private\/Files\/Storage\/Local.php#298"}
```
This is a 500 server error for the client, which lets the client blacklist the file.

After renaming the file back to something shorter, sync is happening correctly and all good.

I'd say that is expected behaviour.
