### ISSUE TITLE
[QA] testing new stuff

### ISSUE THREAD

**Issue by TheOneRing** [owncloud/client#9633]
oCIS test systems: https://owncloud.dev/ocis/deployment/continuous_deployment/
oCIS demo users: https://owncloud.dev/ocis/getting-started/demo-users/
oCIS docker: https://owncloud.dev/ocis/getting-started/#docker

Server used for testing: https://ocis.owncloud.com - if no other server mentioned
 
Upload files/folders from Windows 10 VFS ON to oCIS (account: einstein) - client version: ownCloud-2.11.0-daily20220503.7416-vfs.x64.msi 
 * [ ] Upload of an empty file -> ❗fails, see https://github.com/owncloud/ocis/issues/3154
 * [x] Upload a small file
 * [x] Upload folderA containing 100 small files
      * [x] Free up space for folderA
 * [x] Upload folderB containing 10 subfolders
 * [x] Upload of a 1 MB file
 * [ ] Upload of a 500 MB file -> ❗fails, see https://github.com/owncloud/client/issues/9638

File/folder share on oCIS - client version: ownCloud-2.11.0-daily20220509.7472-vfs.x64.msi
* [x] Client: start client and add account 'katherine'
* [x] Browser: login to oCIS with account 'katherine'
* [x] Browser: create a new folder / share with 'einstein'
* [ ] Client: "Open in Explorer" for 'katherine' -> ❗new folder isn't synced automatically only on "Force snyc"
* [x] Client: add account 'einstein'
* [ ] Client: "Open in Explorer" for 'einstein' -> ❗shared folder not synced, also not on "Force sync", known server issue: the folder isn't shared with 'einstein' -> retest with oCIS Beta

oCIS spaces (account: katherine) - client version: ownCloud-2.11.0-daily20220509.7472-vfs.x64.msi
* [x] Login to oCIS in browser with account 'katherine', create a new space and share with 'einstein' as Editor
  * [x] start client, connect to oCIS, user 'katherine' 
  * [x] space 'Personal' and the new space are shown
  * [x] add account 'einstein'
  * [x] space 'Personal' and the shared space are shown
  * [x] add a file to the shared space
* [x] Start client and connect as user 'katherine'
  * [x] space 'Personal' is shown 
  * [x] login to ocis.owncloud.com and create a new space 'NewSpace'
  * [ ] 'NewSpace' should be shown on client-side -> ❗not shown 
  * [x] click button "Add space" and select 'NewSpace'
  * [ ] 'NewSpace' should be added -> ❗not added correctly, spinning icon remains  -> https://github.com/owncloud/client/issues/9649
* [ ] Change the client language and check the naming of space 'Personal'

Uploads to oCIS (tus)
* [ ] Upload a big file / pause sync / resume sync
* [ ] File is uploaded correctly
* [ ] ...

Connection Wizard - client version: ownCloud-2.11.0-daily20220509.7472-vfs.x64.msi
* [x] Connect to demo.owncloud.org (basic auth)
* [x] Connect to ocis.owncloud.com (oauth)
* [x] Logout from both accounts / Login again 

Folder Wizard

Testdata: 
[data.gz](https://github.com/owncloud/client/files/8620467/data.gz)

**Comment by gabi18** [comment]
Testing continues on https://github.com/owncloud/client/issues/9689
