### ISSUE TITLE
[QA][gui-tests] Wait for files to sync after adding user to the client

### ISSUE THREAD

**Issue by sushmita56** [owncloud/client#9939]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the QA issue

Some of our test scenarios are failing in CI due to the absence of appropriate wait. [for example](https://github.com/owncloud/client/issues/9850). So, after adding a user to the client, we must *wait for resources to sync* for at least a few seconds. For example, in the below scenario, we must wait for files to sync after adding user `Brian` to the client. It is a good practice to wait for resources to sync as soon as we add a user to the client. 

```
Scenario: sharee edits content of files shared by sharer
        Given user "Alice" has created folder "simple-folder" on the server
        And user "Alice" has uploaded file with content "file inside a folder" to "simple-folder/textfile.txt" on the server
        And user "Alice" has uploaded file with content "file in the root" to "textfile.txt" on the server
        And user "Brian" has been created on the server with default attributes and without skeleton files
        And user "Alice" has shared folder "simple-folder" on the server with user "Brian" with "all" permissions
        And user "Alice" has shared file "textfile.txt" on the server with user "Brian" with "all" permissions
        And user "Brian" has set up a client with default settings
        When the user overwrites the file "textfile.txt" with content "overwrite file in the root"
        And the user overwrites the file "simple-folder/textfile.txt" with content "overwrite file inside a folder"
        And the user waits for the files to sync
        Then as "Brian" the file "simple-folder/textfile.txt" on the server should have the content "overwrite file inside a folder"
        And as "Brian" the file "textfile.txt" on the server should have the content "overwrite file in the root"
        And as "Alice" the file "simple-folder/textfile.txt" on the server should have the content "overwrite file inside a folder"
        And as "Alice" the file "textfile.txt" on the server should have the content "overwrite file in the root"
```

#### Todo:

- [x] Look for such scenarios
- [x] Add wait for resources to sync after setting up the client

**Comment by amrita-shrestha** [comment]
![image](https://user-images.githubusercontent.com/54478846/180747551-4a40757d-c3dc-482b-a518-36cde3a0496d.png)
GUI Logs: https://cache.owncloud.com/public/owncloud/client/12592/guiReportUpload/index.html

**Comment by amrita-shrestha** [comment]
List of tests suites:
- [ ] tst_addAccount 
- [ ] tst_checkAlltabs
- [ ] tst_deletFilesFolders
- [ ] tst_editFiles
- [ ] tst_loginLogout
- [ ] tst_removeAccountConnection
- [ ] tst_sharing (@sushmita56 ) https://github.com/owncloud/client/pull/9938
- [ ] tst_syncing
- [ ] tst_vfs

**Comment by saw-jan** [comment]
Will be continued after https://github.com/owncloud/client/issues/10140 is fixed
