### ISSUE TITLE
[QA] Some GUI tests fail in CI with the problem of grayed sync status in AUT

### ISSUE THREAD

**Issue by sushmita56** [owncloud/client#9955]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the QA issue

Some scenarios are failing frequently in CI while running the GUI test and the following screenshot is generated. Mostly the failed scenarios are from the syncing process.

### Screenshot
![grayout](https://user-images.githubusercontent.com/66173400/180944321-89d857b4-5dff-4b2d-a4f7-fdc6f40871ef.png)

 Failed scenario:
- `various types of files can be synced from server to client`
- `Modify orignal content of a file with special character`

### Similar issue
- https://github.com/owncloud/client/issues/9784
- https://github.com/owncloud/client/issues/9794

### Todo:
- [ ] Figure out if the grayed-out sync behavior of AUT is the reason behind the failure

**Comment by saw-jan** [comment]
This problem is due to this issue https://github.com/owncloud/client/issues/9952. I have confirmed it locally.
If `gnome-keyring` is not available (running) then this will happen.

S0, closing this in favor of #9952
