### ISSUE TITLE
[QA] Resources doesn't  visible in `Add Folder Sync Connection` dialogue box

### ISSUE THREAD

**Issue by amrita-shrestha** [owncloud/client#9971]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the QA issue
Then the sync all checkbox should be checked 
```
LookupError: Object '{column='0' container={aboveWidget={text='Deselect remote folders you do not wish to synchronize.' type='QLabel' unnamed='1' visible='1' window={type='OCC::FolderWizard' unnamed='1' visible='1' windowTitle='Add Folder Sync Connection'}} type='QTreeWidget' unnamed='1' visible='1' window={type='OCC::FolderWizard' unnamed='1' visible='1' windowTitle='Add Folder Sync Connection'}} text='ownCloud' type='QModelIndex'}' not found. Could not match properties:
for object name: '{column='0' container={aboveWidget={text='Deselect remote folders you do not wish to synchronize.' type='QLabel' unnamed='1' visible='1' window=:add_Folder_Sync_Connection_OCC_FolderWizard} type='QTreeWidget' unnamed='1' visible='1' window=:add_Folder_Sync_Connection_OCC_FolderWizard} text='ownCloud' type='QModelIndex'}'
LOG06:10:40
Deleting: Alice
```

### Steps to reproduce the issue
```
    Scenario: Sync all is selected by default
        Given user "Alice" has created folder "simple-folder" on the server
        And user "Alice" has created folder "large-folder" on the server
        And the user has started the client
        And the user has added the following account information:
            | server   | %local_server% |
            | user     | Alice          |
            | password | 1234           |
        When the user selects configure_synchronization_manually option in advanced section
        And the user "Alice" clicks on the next button in sync connection wizard
        And the user selects "ownCloud" as a remote destination folder
        Then the sync all checkbox should be checked 
```

### Screenshots
<details>

![image](https://user-images.githubusercontent.com/54478846/182101033-752ec51e-73d5-4bf9-b5dc-3d953b4ca9de.png)

![image](https://user-images.githubusercontent.com/54478846/182101137-d8b6b1a0-e617-4572-8bbb-7c7ce63754f8.png)
</details>
<details>
<summary>GUI Log Screenshot</summary>

![Screenshot from 2022-08-01 13-36-52](https://user-images.githubusercontent.com/54478846/182100577-82a46838-b35f-4932-9ffa-11ffb39efd24.png)
</details>

### Serverlog
[serverlog.log](https://github.com/owncloud/client/files/9232007/syncserverlog.log)

### Client version number
Version 3.0.0(master branch)

## TODO
Failing tests are skipped in PR https://github.com/owncloud/client/pull/9989
- [ ] unskip the tests after the issue has been fixed (https://github.com/owncloud/client/pull/9990)

**Comment by amrita-shrestha** [comment]
Investigation findings:
In the `Add Folder Sync Connection` dialogue box, there should exist resources created in server.
![Screenshot from 2022-07-29 11-53-24](https://user-images.githubusercontent.com/54478846/181694185-59cd4508-7862-41b8-ade6-aca9185ec36c.png)

@TheOneRing  Is this correct behavior?

**Comment by TheOneRing** [comment]
Can't reproduce locally.
This view is asynchronous so maybe a sleep could help.

**Comment by amrita-shrestha** [comment]
@TheOneRing sleep doesn't help. The client version is 3.0.0. 
This issue is reproduced at every nightly build and locally.
Could you rebuild client and try to reprodunce:
```
Scenario: Sync all is selected by default
    Given user "Alice" has created folder "simple-folder" on the server
    And user "Alice" has created folder "large-folder" on the server
    And the user has started the client
    And the user has added the following account information:
        | server   | %local_server% |
        | user     | Alice          |
        | password | 1234           |
    When the user selects configure_synchronization_manually option in advanced section
    And the user "Alice" clicks on the next button in sync connection wizard
    And the user selects "ownCloud" as a remote destination folder
    Then the sync all checkbox should be checked 
```

**Comment by sushmita56** [comment]
Failed again on today's nightly build 
![Screenshot from 2022-08-02 09-35-03](https://user-images.githubusercontent.com/66173400/182287906-8446c91d-60bb-4de0-a8b3-5d612b2b4c61.png)

**Comment by saw-jan** [comment]
This can be reproduced manually. Here is the video record:

https://user-images.githubusercontent.com/52366632/182306005-4783a9bd-d688-4c4b-86c3-9e020b49580e.mp4

@TheOneRing, the last window of `Add Folder Sync Connection` wizard doesn't contain the files list table with checkboxes. Is that the expected one?

**Comment by saw-jan** [comment]
@TheOneRing I concluded that this problem started from this commit: 
[`db73340fb33ecfe081ecb4764e6ff939b870e8bc`](https://github.com/owncloud/client/tree/db73340fb33ecfe081ecb4764e6ff939b870e8bc) `Only set the default sync root from the folder wizard if needed`

**Comment by TheOneRing** [comment]
Thx for reporting.
Should be fixed in https://github.com/owncloud/client/pull/9990
